### ISSUE TITLE
[Wiki] Descriptions for Placeholders

### ISSUE THREAD

**Issue by KissOfFate** [GeorgH93/MarriageMaster#104]
None of the placeholders have descriptions, and some are obvious but others arent. I'd also like to ask if there is a placeholder that will produce a heart if they are married and an empty string if they arent?

**Comment by GeorgH93** [comment]
You can use the "%marriagemaster_heart%" placeholder by changing the [NotMarried.Default](https://github.com/GeorgH93/MarriageMaster/blob/master/resources/lang/en.yml#L337) string in the language file to an empty string (`Default: ""`), this will however change it for all placeholders.
Alternative you can check the [v2.1 alpha](https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/) which will allow to change formatting and messages for all placeholders individually in the language file.

**Comment by GeorgH93** [comment]
The [wiki page](https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders) now has descriptions for all placeholders. It now also includes the new v2.1 placeholders and how the formatting of them can be changed.
