### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by Neos2K** [GeorgH93/MarriageMaster#106]
*Marriage master v2.0.21 : Server v 1.15.1

yes 

no 

I have all the default config settings (I have not changed anything since getting the plugin)

```

### Details
**Description**  
<!-- I have absolutely no idea what is going on. I have OP on a Aternos server that I created and I've added the plugin yet whenever I attempt to use a command in game such as "/marry", it gives me a red text message saying "You don't have the permission to do that." I also noticed a lack of commands displayed when I input "/marry help" Usually when I look at tutorials for this plugin there are a lot of commands being displayed whereas mine are limited to to few. Example: There is no /marry priest or set priest option or  /marry update or /marry reload. It does not appear in the list of /marry help commands in game.-->

**Steps to reproduce**  
<!-- Typed /marry "Player name" "Player name" and it denied me the request because I supposedly don't have permissions. -->

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

<!--My apologies if I deleted something I wasn't supposed to or provided insufficient information as I am quite inexperienced. -->

**Comment by GeorgH93** [comment]
Which permission plugin are you using?

**Comment by Neos2K** [comment]
> Which permission plugin are you using?

PermissionsBukkit v2.5

Is there another one you may recommend?

**Comment by Neos2K** [comment]
> > Which permission plugin are you using?
> 
> PermissionsBukkit v2.5
> 
> Is there another one you may recommend?

I also noticed this in the log. Maybe it has something to do with it? Again forgive me but I'm not at all fluent with code 

[Server thread/WARN]: Plugin PermissionsBukkit v2.5 does not specify an api-version.

**Comment by Neos2K** [comment]
> Which permission plugin are you using?

Aquatic Perms 1.0

It's a permissions plugin that allows the user to give permissions to any player. I only use this server as a private server to play with my friends. Previously I had no permissions plugin but I added this one since I started having this problem. 

Commands:
/perm add <User|*> <Node> -- Add a permission to a user or everyone (*)
/perm remove <User|*> <Node> -- Remove a permission from a user or everyone (*)
/perm test <User|*> <Node> -- Test if someone has a permission
/perm list <User|*> -- List someone's permissions

I don't know what the "permission nodes" for MarrigaeMaster are.

**Comment by GeorgH93** [comment]
So you where not using a permission plugin previously?
I have just tested it with Aquatic Perms and had no problems.
You can try to manually give yourself the `marry.admin` permission (should give everything that is normally given to ops) and your players (including yourself) the `marry.user` permission (should give everything that is normally given by default).

**Comment by Neos2K** [comment]
Yes I was not previously using any permission plugin yet it still gave me the "You do not have permission to do that" Message whenever I tried using a MarriageMaster command. I just tried giving myself permissions with aquatic perms but it also does not seem to be working. I typed /pernissions add (User) (marry.admin) in game and it said "No permission" Is there something I may have to change in the plugin files? I appreciate your help and you are welcome to join my server and help me if you are willing and have the time.

**Comment by Neos2K** [comment]
It's also worth noting that I have other plugins with admin and normal user commands but they seem to be working fine. I can use every command on them. I did not even need to add permissions with aquatic perms

**Comment by Neos2K** [comment]
Is there supposed to be a permission section in the plugin file code. I mean in the .yml 
I don't see one

**Comment by GeorgH93** [comment]
Yes, there should be one. Should look like this: https://github.com/GeorgH93/MarriageMaster/blob/master/resources/plugin.yml
If it is missing please try to re-download the jar file.

**Comment by Neos2K** [comment]
I've re-downloaded the file several times and the permissions code just never appears. It may that Aternos uploaded a faulty file? in any case. Is there a way I can just add the permissions part of the code in there?

**Comment by GeorgH93** [comment]
Could you please provide me a list of your installed plugins (/pl should list them all)

**Comment by Neos2K** [comment]
Thank you for your help. I appreciate the effort that you put into trying to fix my problem however I've found a solution and no longer need assistance. Thank you!
