### ISSUE TITLE
on marry commands not working in new update

### ISSUE THREAD

**Issue by FallingCactus** [GeorgH93/MarriageMaster#107]
### Information
**Environment information**
*Plugin + server version info*:

```

<!-- 23.01 07:07:45 [Server] Startup [12:07:45 INFO]: ##### Start Marriage Master version info #####
23.01 07:07:45 [Server] Startup [12:07:45 INFO]: Marriage Master: 2.1-Release
23.01 07:07:45 [Server] Startup [12:07:45 INFO]: Server: git-Paper-67 (MC: 1.15.2)
23.01 07:07:45 [Server] Startup [12:07:45 INFO]: MVdWPlaceholderAPI: 3.0.1
23.01 07:07:45 [Server] Startup [12:07:45 INFO]: PlaceholderAPI: 2.10.4
23.01 07:07:45 [Server] Startup [12:07:45 INFO]: #####  End Marriage Master version info  #####. -->

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- https://gist.github.com/FallingCactus/2bef14716cff226b4ba6a39a61f1487e -->

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Is there anything in the log when players get married?

**Comment by FallingCactus** [comment]
> Is there anything in the log when players get married?

`24.01 09:47:01 [Server] INFO [14:47:01 INFO]: FallingCactus issued server command: /marry FallenCactus
24.01 09:47:09 [Server] INFO [14:47:09 INFO]: FallenCactus issued server command: /marry accept
24.01 09:47:10 [Server] Startup [14:47:09 INFO]: FallingCactus has married FallenCactus.`

no errors, just does not issue the commands set in config.

**Comment by GeorgH93** [comment]
Fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/lastSuccessfulBuild/artifact/artifacts/MarriageMaster-2.1.1-Release.jar
