### ISSUE TITLE
Commands Seen & TP fail to work

### ISSUE THREAD

**Issue by Alejandro-Sosa** [GeorgH93/MarriageMaster#108]
The Commands /marry seen and /marry tp both don't work anymore. I'm using Paper #77 1.15.2

Console shows the following warning:

[WARNING] .... [MarriageMaster] Unhandled exception executing command 'marry' in plugin MarriageMaster v2.1.1-Release

[WARNING] .... java.lang.NullPointerException

[WARNING] .... at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.TpCommand.execute(TpCommand.java:98)

[WARNING] .... at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.TpCommand.execute(TpCommand.java:42)

[WARNING] .... at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:150)

[WARNING] .... at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:35)

[WARNING] .... at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:165)

[WARNING] .... at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:134)

[WARNING] .... at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)

[WARNING] .... at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628)

[WARNING] .... at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)

[WARNING] .... at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4280.000000008C174740.run(Unknown Source)

[WARNING] .... at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)

[WARNING] .... at java.lang.Thread.run(Thread.java:813)

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/143/artifact/artifacts/MarriageMaster-2.1.2-Release.jar

**Comment by Alejandro-Sosa** [comment]
It works! Thank you so much for the quick support i didn't expect it to be solved so soon.
