### ISSUE TITLE
[Suggestion] Players' names in notifications

### ISSUE THREAD

**Issue by Srborjaa** [GeorgH93/MarriageMaster#109]
Hi there!
It could be a good idea to show the nick of the partner that connects and disconnects. An example could be:

PartnerNowOnline: Your partner (NickOfPartner) is now online.
PartnerNowOffline: Your partner (NickOfPartner) is now offline.

Thanks!

**Comment by GeorgH93** [comment]
You can change that in the [language file](https://github.com/GeorgH93/MarriageMaster/blob/master/resources/lang/en.yml#L26-L27).
Just change it like this:
```
      PartnerNowOnline: "[\"\",{\"text\":\"Your partner {Name} is now online.\",\"color\":\"green\"}]"
      PartnerNowOffline: "[\"\",{\"text\":\"Your partner {Name} is now offline.\",\"color\":\"gray\"}]"
```
or this:
```
      PartnerNowOnline: "[{\"text\":\"Your partner \",\"color\":\"green\"},{\"text\":\"{DisplayName}\"},{\"text\":\" is now online.\"}]"
      PartnerNowOffline: "[{\"text\":\"Your partner \",\"color\":\"gray\"},{\"text\":\"{DisplayName}\"},{\"text\":\" is now offline.\"}]"
```

**Comment by Srborjaa** [comment]
Thanks. Another issue that I have is that the placeholder only shows one nick, instead of showing all names, separated by commas.

https://i.gyazo.com/ecfdf59dd17b7505da21ab3e45813dc0.png

**Comment by GeorgH93** [comment]
You are using the `%marriagemaster_PartnerList%` or `%marriagemaster_PartnerDisplayNameList%` placeholder?

**Comment by Srborjaa** [comment]
Oh, I didn't see them in the wiki.

Thanks and sorry for the inconveniences.

**Comment by z3030823844** [comment]
### Excuse me, is this already configured?

1. PartnerNowOnline: "[{\"text\":\"Your partner \",\"color\":\"green\"},{\"text\":\"{DisplayName}\"},{\"text\":\" is now online.\"}]"
2.       PartnerNowOffline: "[{\"text\":\"Your partner \",\"color\":\"gray\"},{\"text\":\"{DisplayName}\"},{\"text\":\" is now offline.\"}]"

**Comment by GeorgH93** [comment]
> 
> ### Excuse me, is this already configured?
> 
>     1. PartnerNowOnline: "[{"text":"Your partner ","color":"green"},{"text":"{DisplayName}"},{"text":" is now online."}]"
> 
>     2. ```
>          PartnerNowOffline: "[{\"text\":\"Your partner \",\"color\":\"gray\"},{\"text\":\"{DisplayName}\"},{\"text\":\" is now offline.\"}]"
>        ```

This has been possible since version 2.0. You just have to change your language file. I will not make it the default since most servers are not allowing more than one partner.
