### ISSUE TITLE
Not being able to marry

### ISSUE THREAD

**Issue by AccioAce** [GeorgH93/MarriageMaster#112]
### Information
**Environment information**
*Plugin + server version info*:
 https://gyazo.com/ec260f8c8514c8b30e14b1f41c8858b2
```

<!-- Replace this with the output of "/marry version". You can run the command in your console or as op ingame. --> https://gyazo.com/ec260f8c8514c8b30e14b1f41c8858b2

```

*Online mode*:  no (Bungee)

*BungeeCord*: 

**Server/crash log**
 Nope
```

<!-- Replace this with your crash log / link to your log file -->

``` 

**Plugin config (optional)**
 I don't use any database.
```

<!-- Replace this with details about your config -->

``` I use the default configuration.

### Details
**Description**  
Players not being able to marry each other.

**Steps to reproduce**  
/marry marry {name} {name} - Which tells a player that they are already married so they can't answer it...

**Expected behavior**  
Players being able to marry other players

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
<!-- Replace this with any additional information, if necessary. -->

**Comment by GeorgH93** [comment]
The default config requires a third player (with either the `marry.priest` permission or that is set as a priest with the `/marry setpriest` command) to marry them.
If you do not want this behavior you can change it in the [config](https://github.com/GeorgH93/MarriageMaster/blob/master/resources/config.yml#L55), by setting `RequirePriest` to `false`. Then players will be able to marry another player without a priest player.

**Comment by AccioAce** [comment]
ah, I see, thank you!
