### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by BillZhucn** [GeorgH93/MarriageMaster#113]
### Help request

**Problem**
I have problem with the Chinese translation. You update the english one and please tell me how to update the translation or help you to make the new translation

**What I have tried**

**Comment by GeorgH93** [comment]
I think the fastest way would be to let the plugin update the language file, it will copy the English value for all the missing keys into the Chinese one and to then translate the new values into Chinese. You can use the [language file editor](https://ptp.pcgamingfreaks.at/) for that, by simply using the ` Userdefined` at the `Choose the language file you want to edit:` section and selecting the Chinese language file created by the plugin.

You can also check the changes to the English language file [here](https://github.com/GeorgH93/MarriageMaster/compare/v2.0.21...v2.1.3#diff-2fc3dbcf0293d0dfd1ad94f544bb2a7d). It might help with figuring out which keys have been added.

**Comment by BillZhucn** [comment]
I finished the translation please help me uploading it.

**Comment by GeorgH93** [comment]
Go [here](https://github.com/GeorgH93/MarriageMaster/edit/master/MarriageMaster/resources/lang/cn.yml).
Replace the content with your updated language file.
Click the Green `Propose file change` button at the end of the page.
That should create a pull request that I can than merge into my repository.

**Comment by BillZhucn** [comment]
Please check.

**Comment by GeorgH93** [comment]
I have merged it. Thank you very much.

**Comment by BillZhucn** [comment]
I will close this issue now. Thanks for your help.
