### ISSUE TITLE
Divorce offline player

### ISSUE THREAD

**Issue by LogGits** [GeorgH93/MarriageMaster#115]
### Help request

**Problem**
Players cannot divorce a player that is offline with `marry.selfdivorce` set. It means that if someone joins for a day and never comes back, a player is stuck with that partner unless staff intervene. Is there a way to make it so they can divorce an offline player.

**What I have tried**
Using the self divorce permission `marry.selfdivorce` & `/marry divorce` (online player with offline partner)

MM version 2.1.3-Release

**Comment by GeorgH93** [comment]
They should be able to divorce offline partners if they have the `marry.offlinedivorce` permission.

**Comment by LogGits** [comment]
:o thankyou so much, that worked
