### ISSUE TITLE
Renamed players can't /marry tp because it still remembers previous name

### ISSUE THREAD

**Issue by TNTUP** [GeorgH93/MarriageMaster#118]
### Information
Windows server 2019 - AdoptJDK 8

[0 22:09:18 INFO]: ##### Start Marriage Master version info #####
[0 22:09:18 INFO]: Marriage Master: 2.1.3-Release
[0 22:09:18 INFO]: Server: git-Paper-"8f7f4cf" (MC: 1.12.2)
[0 22:09:18 INFO]: MinePacks: 1.17.12-SNAPSHOT
[0 22:09:18 INFO]: PlaceholderAPI: 2.10.3
[0 22:09:18 INFO]: #####  End Marriage Master version info  #####

[0 22:09:54 INFO]: This server is running Paper version git-Paper-"8f7f4cf" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[0 22:09:54 INFO]: Previous version: git-Paper-"2ee16de" (MC: 1.12.2)
[0 22:09:54 INFO]: Checking version, please wait...
[0 22:09:54 INFO]: You are 5 version(s) behind

*Online mode*: Yes

*BungeeCord*: Yes

**Server/crash log**
No crash logs or errors

**Plugin config (optional)**

[configREDACTED.txt](https://github.com/GeorgH93/MarriageMaster/files/4333706/configREDACTED.txt)

### Details
**Description**  
Players which changes their name PlayerA to PlayerDFASDF still shows PlayerA in the married partner meaning the PlayerZ which is married to PlayerDFASDF cannot /marry tp because the database still remembers the previous name.

**Steps to reproduce**  
Marry 2 players and ask one to change their name. Let it log on the server then try /marry tp on a bungee network. Not sure if its non reproducible on a non bungee setup.

**Expected behavior**  
Plugin should check if the name/uuid matches and update if necessary.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

The way how I explain things are really bad so pardon me if its non understandable, trying to explain something is quite hard for me x)

**Comment by GeorgH93** [comment]
Fixed a couple bugs with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/158/artifact/artifacts/MarriageMaster-2.1.4-RC2-Release.jar) (please update all your servers to this, including the BungeeCord), please try if it resolves the problem for you.

Also your Minepacks version is very old you should probably update it (please update to v1.19.2 before updating to v2.x to prevent corrupted backpacks on newer MC versions).

**Comment by TNTUP** [comment]
> Fixed a couple bugs with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/158/artifact/artifacts/MarriageMaster-2.1.4-RC2-Release.jar) (please update all your servers to this, including the BungeeCord), please try if it resolves the problem for you.
> 
> Also your Minepacks version is very old you should probably update it (please update to v1.19.2 before updating to v2.x to prevent corrupted backpacks on newer MC versions).

Will test it shortly.

I don't see the intention to update it as the changes doesn't affect me, but oh well I'll update it anyways this evening/night ^^

**Comment by TNTUP** [comment]
edit: that minepacks version is from the v1 server (1.12.2) which the v2 (1.15.2) is on 2.1.1. Shall I update all of them to 2.x even on 1.12.2?

**Comment by GeorgH93** [comment]
> 
> 
> > Fixed a couple bugs with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/158/artifact/artifacts/MarriageMaster-2.1.4-RC2-Release.jar) (please update all your servers to this, including the BungeeCord), please try if it resolves the problem for you.
> > Also your Minepacks version is very old you should probably update it (please update to v1.19.2 before updating to v2.x to prevent corrupted backpacks on newer MC versions).
> 
> Will test it shortly.
> 
> I don't see the intention to update it as the changes doesn't affect me, but oh well I'll update it anyways this evening/night ^^

If you like you can stay on that version, but you should keep in mind that if you ever want to update to MC 1.13 or newer you should have run v1.19.2 at least once since I had to change the storage format and only v1.19 builds are batch converting all old backpacks into the new storage format.
Also v2.x has changed a lot under the hood for improved performance and better protection against data-loss by detecting problems. These changes however effect the compatibility with Marriage Master and I don't know how long I will keep the compatibility with v1.x Minepacks in Marriage Master.



> 
> 
> edit: that minepacks version is from the v1 server (1.12.2) which the v2 (1.15.2) is on 2.1.1. Shall I update all of them to 2.x even on 1.12.2?

It's up to you, v2.x is fully compatible with MC 1.12.2. If you don't care about the new features you could just stay on v1.x. But I would at least update it to v1.19.2 so that you have all your backpacks in the new storage format.

**Comment by TNTUP** [comment]
> > > Fixed a couple bugs with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/158/artifact/artifacts/MarriageMaster-2.1.4-RC2-Release.jar) (please update all your servers to this, including the BungeeCord), please try if it resolves the problem for you.
> > > Also your Minepacks version is very old you should probably update it (please update to v1.19.2 before updating to v2.x to prevent corrupted backpacks on newer MC versions).
> > 
> > 
> > Will test it shortly.
> > I don't see the intention to update it as the changes doesn't affect me, but oh well I'll update it anyways this evening/night ^^
> 
> If you like you can stay on that version, but you should keep in mind that if you ever want to update to MC 1.13 or newer you should have run v1.19.2 at least once since I had to change the storage format and only v1.19 builds are batch converting all old backpacks into the new storage format.
> Also v2.x has changed a lot under the hood for improved performance and better protection against data-loss by detecting problems. These changes however effect the compatibility with Marriage Master and I don't know how long I will keep the compatibility with v1.x Minepacks in Marriage Master.
> 
> > edit: that minepacks version is from the v1 server (1.12.2) which the v2 (1.15.2) is on 2.1.1. Shall I update all of them to 2.x even on 1.12.2?
> 
> It's up to you, v2.x is fully compatible with MC 1.12.2. If you don't care about the new features you could just stay on v1.x. But I would at least update it to v1.19.2 so that you have all your backpacks in the new storage format.

Well, the Skyblock/AcidIsland/Legacy main servers are stuck on 1.12.2. However, I'm planning to update MarriageMaster and MinePacks (first 1.19.2 then to 2.x) on them (1.12.2) and servers which are on 1.15.2 will be updated to their latest versions. 

Thanks for your time and the fix! Love your plugins <3

**Comment by TNTUP** [comment]
Seems to be fixed. However, getting this stacktrace when a new player joins. Shall I create a seperate issue?

**Comment by GeorgH93** [comment]
I am working on a solution for that problem. Opening a separate issue should not be necessary.

**Comment by TNTUP** [comment]
> I am working on a solution for that problem. Opening a separate issue should not be necessary.

Okie! Take your time :)

**Comment by TNTUP** [comment]
Any updates? The deadlock still prints when a new player joins :( harmless though xD

**Comment by GeorgH93** [comment]
> 
> 
> Any updates? The deadlock still prints when a new player joins :( harmless though xD

I have been testing a mitigation for the problem for some time now. It does not seem to cause any unexpected side effects for now (will be included in the next update). If you would like to test it, you can use [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/198/artifact/artifacts/MarriageMaster-2.1.9-Release.jar).

**Comment by TNTUP** [comment]
> > Any updates? The deadlock still prints when a new player joins :( harmless though xD
> 
> I have been testing a mitigation for the problem for some time now. It does not seem to cause any unexpected side effects for now (will be included in the next update). If you would like to test it, you can use [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/198/artifact/artifacts/MarriageMaster-2.1.9-Release.jar).

Will do test it on the next server maintenance (maybe this night) and I'll let you know :D
