### ISSUE TITLE
Global marry chat not working

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [GeorgH93/MarriageMaster#121]
### Information
**Environment information**
*Plugin + server version info*:

```

24.03 02:41:39 [Server] INFO ##### Start Marriage Master version info #####
24.03 02:41:39 [Server] INFO Marriage Master: 2.1.4-RC2-Release
24.03 02:41:39 [Server] INFO Server: git-Paper-125 (MC: 1.15.2)
24.03 02:41:39 [Server] INFO Java: 11.0.6
24.03 02:41:39 [Server] INFO Vault: 1.6.11
24.03 02:41:39 [Server] INFO MVdWPlaceholderAPI: 3.0.1
24.03 02:41:39 [Server] INFO PlaceholderAPI: 2.10.4
24.03 02:41:39 [Server] INFO #####  End Marriage Master version info  #####


```

*Online mode*: 

*BungeeCord*: yes

### Details
**Description**  
Im using bungeecord with paperspigots on 1.15.2. /marry tp is correctrly working from server to server, but /marry chat says that partner is offline if he is on other server. I have installed marriagemaster on Bungee, enabled global chat there and enabled bungee in spigots configs (as /marry tp is working fine)

**Comment by GeorgH93** [comment]
Tried to reproduce this but was not able to.
Are you using any plugins that do processing on chat on your BungeeCord server?
