### ISSUE TITLE
Bungee Console Error

### ISSUE THREAD

**Issue by LucidAPs** [GeorgH93/MarriageMaster#123]
Minecraft 1.15.2
Waterfall : 326
Paper: 143
Marry version: https://pastebin.com/raw/Uys5hWYV

BungeeCord online mode!

Server/crash log from bungee console:  https://pastebin.com/raw/ft8Ni9XQ

**Comment by GeorgH93** [comment]
Please update to this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/159/artifact/artifacts/MarriageMaster-2.1.4-RC2-Release.jar

**Comment by LucidAPs** [comment]
I used the version MarriageMaster-2.1.4-RC2-Release.jar and it fixed the above problem but i am getting a new error now.

https://pastebin.com/raw/WrWSzACJ

**Comment by GeorgH93** [comment]
Could you please provide me with the startup log.

**Comment by LucidAPs** [comment]
Sure, here it is
[latest.log](https://github.com/GeorgH93/MarriageMaster/files/4390423/latest.log)

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://github.com/GeorgH93/MarriageMaster/releases/download/v2.1.4/MarriageMaster-2.1.4-Release.jar

**Comment by LucidAPs** [comment]
Yeap that version fixed it, thanks.
