### ISSUE TITLE
Error with bungeecord + data no longer works between my servers

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#124]
Hello, I am currently using the version of marriagemaster 2.1.3, I currently have 2 problems:
- Error on bungee logs (http://bin.mc-imperia.fr/YvANBLTUn1)
- Synchronization between my bungee servers no longer works.
Paper version: 146
Waterfall version: 326

**Comment by GeorgH93** [comment]
Please update the plugin on the BungeeCord to this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/160/artifact/artifacts/MarriageMaster-2.1.4-RC3-Release.jar

**Comment by jere62smi** [comment]
Okay perfect, I no longer have the error!
