### ISSUE TITLE
Bungee Failed Connection Database

### ISSUE THREAD

**Issue by LucidAPs** [GeorgH93/MarriageMaster#126]
MC 1.15.2
Bungee / Waterfall : 326
Plugin: 165

https://pastebin.com/raw/XFn2geRE

**Comment by GeorgH93** [comment]
Your user does not have the permission to connect to the database.
Make sure that the user is correct and has the permissions to access the database. And it looks like you are connecting to a remote MySQL server so make sure that your user is allowed to make connections from the server your Waterfall is running on.
