### ISSUE TITLE
Changing default Permissions

### ISSUE THREAD

**Issue by Exillium313** [GeorgH93/MarriageMaster#127]
### Help request

**Problem**

I only want players of a certain to rank to be able to marry someone, its an ingame rank.
**What I have tried**

I am using Luckperms so I added marry.user "false" to the default group that all other ranks inherit from, and then made a group called "marry" added marry.user to true, and set a few of the perms that it provides to false Chat Formatting and self divorce/marry.  Problem is the ingame rank inherits from both Default and Marry, resulting in the permissions being negated even if you have the rank.  I know this is a limitation of how LuckPerms does its permissions, but I didnt see a way to change the default permissions given to players.

Any help would be greatly appreciated.

Thank you!

**Comment by GeorgH93** [comment]
Found a workaround. Use `marry.*` in the default permission to deny the usage of the plugin. Then you should be able to add the permissions with the `marry.user` permission group with another group.

**Comment by Exillium313** [comment]
Will try this, thank you!

**Comment by Exillium313** [comment]
So this somewhat worked... I have 2 tracks for promotion.  Ingame and Donor, so default is inherited through Barbarian ( 1st ingame rank ) and Saint ( 1st donor rank ).  Setting like you said, makes it work correctly for Saint, but none of the other donor ranks... Even adding the base permission group.default to higher donator ranks, so its directly inherited rather then through the ranks. Still wont work...

Is there anyway to just make the default permissions configurable?

**Comment by GeorgH93** [comment]
According to the luckperms wiki `Wildcard/regex permissions will be overridden by normal permissions` and `Inherited permissions will be overridden by an objects own permissions.` so you could try to give the permissions you would like your group to have directly instead of using the `marry.user` group.

The plugin is open source, so you can just change the default values in the `plugin.yml` and compile the plugin yourself and disable the auto update feature.
Or use the official builds and change the `plugin.yml` inside the .jar file manually every update, you should also disable the auto update feature in this case.

**Comment by Exillium313** [comment]
Ahh perfect, I'll jump compile myself

**Comment by Exillium313** [comment]
I am struggling to compile this myself, I've only limited knowledge with this, taking some beginner java classes working with IntelliJ but importing someone else's code is new to me.

I modified the plugin.yml permissions, to my liking, if I upload it for you could you make a fork with no default permissions?

Sorry, I tried importing into IntelliJ and then exporting but I didnt get the jar.  Tried doing it through Git too, but that wanted to add a fork to your github

**Comment by GeorgH93** [comment]
You can click the fork button on the top right of this page. It will then create a fork on your account. If you change things there they will stay on your fork, and you should be able to update your fork easily with a pull request.

Building the plugin needs maven. You can use IntelliJ to build it with Maven by creating a new `Run Configuration` with the type Maven.
Set the `Working directory` to the folder of your downloaded source code. The `Command line` to `clean package` and the `Profiles` to `Standalone ExcludeBadRabbit`.
If you then Run this configuration it will compile the plugin and once it is done you should find a `MarriageMaster-<CurrentVersion>-Standalone.jar` file in the `MarriageMaster/target` folder.
