### ISSUE TITLE
Marry chattoggle not working

### ISSUE THREAD

**Issue by wanskae** [GeorgH93/MarriageMaster#128]
When writing the command '/marry chattoggle' it announces I switched to private marry chat, but the messages still appear in global chat. I am using VentureChat on Paper Spigot (version 1.15.2).

![image](https://user-images.githubusercontent.com/63206547/78507197-6363da00-7787-11ea-976f-781501626f77.png)

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/169/artifact/artifacts/MarriageMaster-2.1.5-RC3-Release.jar
