### ISSUE TITLE
mcmmo error

### ISSUE THREAD

**Issue by Kbryst** [GeorgH93/MarriageMaster#129]
Just seeing an error in the console with mcmmo exp and marriage master
https://pastebin.com/t93WCfZc

MarriageMaster 2.1.4-release
Using mcmmo official (not classic)

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/171/artifact/artifacts/MarriageMaster-2.1.5-RC4-Release.jar).
