### ISSUE TITLE
Problem with the marriages cat during the divorce.

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#131]
Hello,
I noticed for a little while that when a player divorces and he is still in the chat of the married then he can no longer use commands from any plugin at all, I am obliged to remarry him from force with a / sudo because it can no longer type commands at all.
Could you check if the player is still in the chat room before proceeding with a divorce?

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/176/artifact/artifacts/MarriageMaster-2.1.6-Release.jar

**Comment by GeorgH93** [comment]
Thanks for letting me know. Should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/177/artifact/artifacts/MarriageMaster-2.1.7-Release.jar

**Comment by jere62smi** [comment]
Okay everything seems to be settled, thank you!
