### ISSUE TITLE
Error lagging the server

### ISSUE THREAD

**Issue by Bublelift** [GeorgH93/MarriageMaster#132]
So i'm getting this error:

[at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.pool.HikariPool]: MarriageMaster-Connection-Pool - Thread starvation or clock leap detected (housekeeper delta=46s426ms304µs149ns).

like once per hour. It causes really big lagg on server, sometimes even kicking the players.

**Comment by GeorgH93** [comment]
That error is caused by the lagg. Whatever caused the lagg also caused the housekeeping thread of the database connection pool to run late.

**Comment by Bublelift** [comment]
Alright, so I believe that it's not the plugin's fault, thanks
