### ISSUE TITLE
Divorce bug

### ISSUE THREAD

**Issue by jordanwilliams1** [GeorgH93/MarriageMaster#139]
Players can't Divorce each other unless there online even if the config is changed in the latest dev builds, 

I'm running #186 didn't see any fix for it in #187 so I'd assume you haven't noticed it. 

config; https://pastebin.com/xwLBapeP

**Comment by GeorgH93** [comment]
Players need the `marry.offlinedivorce` permission in order to be able to divorce an offline partner.

**Comment by jordanwilliams1** [comment]
@GeorgH93 Thank you. I didn't bother to read the changes. thanks for the speedy response.
