### ISSUE TITLE
EssentialsX  PAPI

### ISSUE THREAD

**Issue by LucidAPs** [GeorgH93/MarriageMaster#140]
So apparently EssentialsX chat doesn't support placeholders from PAPI, is there anything i can do so that the MM placeholders show up correctly in chat?

**Comment by GeorgH93** [comment]
Essentials chat should be compatible with the [Prefix/Suffix](https://github.com/GeorgH93/MarriageMaster/blob/cde4bfbae7ff01740823732e7bb31ccceb3c78e2/MarriageMaster/resources/config.yml#L84-L95) config options, they will not give you as much freedom as PAPI, but still be better than nothing.

**Comment by LucidAPs** [comment]
Thank you for the help, is it possible for the {StatusHeart} to be put on the suffix aswell because it only works on prefix. Also having the IsMarried as an option would be amazing.

**Comment by GeorgH93** [comment]
[This build](https://ci.pcgamingfreaks.at/job/MarriageMaster/191/artifact/artifacts/MarriageMaster-2.1.9-RC3-Release.jar) should make the `{StatusHeart}` and the `{MagicHeart}` Placeholders also work as a suffix.
How would you use the IsMarried placeholder in your chat message?

**Comment by LucidAPs** [comment]
That is great news thank you so much! I made a mistake, i meant to ask about the Heart placeholder. I would really like for the heart to appear only when someone is married. That is the best placeholder :)

**Comment by GeorgH93** [comment]
Everything in the prefix/suffix will only get added to the chat if the player is married. If the prefix/suffix contains a `{StatusHeart}` a gray :heart: will be added for not married players.
If there should only be an heart if they are married you can set the prefix/suffix `String` option to only an `<heart>` which will be replaced with an :heart: .
