### ISSUE TITLE
Plugin is not loading in most recent tuinity versions

### ISSUE THREAD

**Issue by LoSCraft-Network** [GeorgH93/MarriageMaster#143]
### Information
**Environment information**
*Plugin + server version info*:
Not able to, plugin does not start, I'm running the lastest version available in spigot
```

<!-- Replace this with the output of "/marry version". You can run the command in your console or as op ingame. -->Not able to, plugin does not start, I'm running the lastest version available in spigot

```

*Online mode*: No

*BungeeCord*: Yes, But not running plugin under Bungee

**Server/crash log**
https://pastebin.com/w6AWx4jm
```

<!-- Replace this with your crash log / link to your log file -->https://pastebin.com/w6AWx4jm

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Plugin does not load

**Steps to reproduce**  
Start the server

**Expected behavior**  
Plugin to start

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
It might be a new version of tuinity that has caused the plugin to become some-what incompatible

**Comment by GeorgH93** [comment]
Have you tried re-downloading/uploading(to the server) the plugin? The log (`Caused by: java.util.zip.ZipException: zip END header not found`) indicates that the plugin file is damaged. You can also check the files integrity with it's checksum, the md5 sum of the latest version should be `cc0560be1208f5904c8d771856425e0b`.

**Comment by LoSCraft-Network** [comment]
I re-downloaded the jar and replaced it

I'll be back with the result later tonight when we restart the server
