### ISSUE TITLE
Suffix heart appears even when configured not to in version 2.1.9

### ISSUE THREAD

**Issue by Momshroom** [GeorgH93/MarriageMaster#144]
### Information
**Environment information**
*Plugin + server version info*:

```

[12:00:34 INFO]: ##### Start Marriage Master version info #####
[12:00:34 INFO]: Marriage Master: 2.1.9-Release
[12:00:34 INFO]: Server: git-Paper-348 (MC: 1.15.2)
[12:00:34 INFO]: Java: 11.0.7
[12:00:34 INFO]: Vault: 1.7.2-b107
[12:00:34 INFO]: MVdWPlaceholderAPI: 3.0.1
[12:00:34 INFO]: PlaceholderAPI: 2.10.6
[12:00:34 INFO]: #####  End Marriage Master version info  #####

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

no marriage master related errors

```

**Plugin config (optional)**

```

https://gist.github.com/Momshroom/c715ba5c57eef5adfceae9b0e0880da7#file-gistfile1-txt

```

### Details
**Description**  
The marriage suffix heart appears in chat even when set not to after updating to the latest release. (It didn't on our last installed version)

**Steps to reproduce**  
 Updated marriage master (and stopped/started the server to do so) 

**Expected behavior**  
 The suffix heart would only appear if the config was set to enable it.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
 https://prnt.sc/syog28

**Comment by Momshroom** [comment]
yes, I'm in online mode... had that in the < >. sorry

**Comment by Momshroom** [comment]
no, I'm not using Bungee

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/199/artifact/artifacts/MarriageMaster-2.1.10-RC1-Release.jar).

**Comment by Momshroom** [comment]
It works.  Tyvm
