### ISSUE TITLE
1.16 Support + BungeeCord

### ISSUE THREAD

**Issue by TNTUP** [GeorgH93/MarriageMaster#145]
### Information
Windows Server 2019 x64 
Marriage Master 2.1.10

```
N/A, plugin errored out
<!-- Replace this with the output of "/marry version". You can run the command in your console or as op ingame. -->

```

*Online mode*: < Yes

*BungeeCord*: Yes

**Server/crash log**
https://pastebin.com/Gb2DdW7V
 

**Plugin config (optional)**

```

https://pastebin.com/A1F70U9a

```

### Details
**Description**  
Plugin errors out when launched with BungeeCord (Build 1502) to add 1.16 support. Guess that RGB they added in 1.16 breaks some plugins.

**Steps to reproduce**  
Get BC#1502 then Marriage Master 2.1.10 from SpigotMC

**Expected behavior**  
Up and running

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
Thats all. Take your time, I'll wait till this gets fixed to allow 1.16 players to join.

**Comment by GeorgH93** [comment]
Looks like 1.16 introduces some breaking bugs. Should be fixed soon.

**Comment by TNTUP** [comment]
> Looks like 1.16 introduces some breaking bugs. Should be fixed soon.

Yeah, I'm expecting that on Spigot side aswell

**Comment by GeorgH93** [comment]
Should be fixed with [this update](https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.2) for both Server and Proxy.

**Comment by TNTUP** [comment]
> Should be fixed with [this update](https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.2) for both Server and Proxy.

Yep, works! Thx :D
