### ISSUE TITLE
Gender Support?

### ISSUE THREAD

**Issue by AngellitoX** [GeorgH93/MarriageMaster#146]
Hello there!

Any chance to implement the gender support? I saw you added it into your milestone in August last year, but haven't seen anything new towards the topic.

It'd be an incredible feature to add.

Thanks!

**Comment by GeorgH93** [comment]
Will be included in the next update (v2.3). Had to push 2.2 a bit earlier than expected because of the MC 1.16 release.

**Comment by GeorgH93** [comment]
Please refer to #45 for more details.
