### ISSUE TITLE
Anytime I update the server (even when updating other mods and not touching this one) all marriages uncouple

### ISSUE THREAD

**Issue by meibeeart** [GeorgH93/MarriageMaster#147]
### Information
**Environment information**
*Plugin + server version info*:

```

<!-- Replace this with the output of "/marry version". You can run the command in your console or as op ingame. -->

```

*Online mode*: 

*BungeeCord*: 

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Whats the output of the "/marry version" command (please provide the full output)?
