### ISSUE TITLE
getting kicked

### ISSUE THREAD

**Issue by threlief** [GeorgH93/MarriageMaster#148]
### Information
**Environment information**
*Plugin + server version info*:

```
marriage master : 2.2.1
server  1.16.1 paper 73
placeholder api:2.10.6

<!-- Replace this with the output of "/marry version". You can run the command in your console or as op ingame. -->

```

*Online mode*: bungee online but the backend ones is not

*BungeeCord*: yes

**Server/crash log**

```no error just ehen someone kisses the both get booted and the message says "
 Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)"
<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```
N/A
<!-- Replace this with details about your config -->
we didnt mess with our config
```

### Details
**Description**  
everytime someone holds shift and kisses thry get booted and gives the message above

**Steps to reproduce**  
made sure it was updated made sure all the plugins we have even deleted it and reuploaded it still does this

**Expected behavior**  
to get hearts and say what it used to say "you have kissed your partner"

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Very interesting.
Which BungeeCord version are you using?
Are you using plugins like ViaVersion, ProtocolSupport? If so, is this a problem for all players or only these that are not using 1.16.1?
Have you modified the message in the language file?

**Comment by threlief** [comment]
no never messed with config yes only on the 1.16.1 server for everyone we are using the new 1.16.1 version of bungee and yes using via and protocol

**Comment by GeorgH93** [comment]
Could you please tell me your ViaVersion and ProtocolSupport version?

**Comment by threlief** [comment]
ViaVersion 3.0.1----- ProtocolLib v4.5.1

**Comment by GeorgH93** [comment]
I have just verified it. The problem is caused by ViaBackwards. I will report it to them.
Till then you will have to take away the kiss permission or replace ViaBackwars with [ProtocolSupport](https://www.spigotmc.org/resources/protocolsupport.7201/) (download for 1.16.1 is linked in the description).

**Comment by threlief** [comment]
we dont have viabackwards though

**Comment by GeorgH93** [comment]
Have you tried removing ViaVersion then? If you don't have ViaBackwards you should not need it when your server is already 1.16.
Also your ProtocolLib is for 1.15.2, you probably should try to update that to [their latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/472/) too.

**Comment by threlief** [comment]
we need viaversion with protocol to allow players to log on any version to the 1.16.1 server
and the protocol was recent update for the 1.16.1 but we will look for newer update and see if it works
