### ISSUE TITLE
Slimefun compatibility

### ISSUE THREAD

**Issue by LozoTrioxide** [GeorgH93/MarriageMaster#149]
### Feature request

**Feature description**
Slimefun backpack support

**How the feature is useful**
As the slimefun plugin backpacks and minepacks plugin backpacks cannot be used together properly, could we have intergration to use slimefun packs instead or as well as minepacks?

**Comment by GeorgH93** [comment]
What is the problem when using both plugins?

**Comment by LozoTrioxide** [comment]
If you're using both slimefun backpacks and minepack backpacks, the console errors when opening a backpack as slimefun thinks its from slimefun, when it is actually from minepacks :<

**Comment by GeorgH93** [comment]
Error is caused by Slimefun. Nothing I can do about it. Please report it to them.
