### ISSUE TITLE
Can't Divorce Players

### ISSUE THREAD

**Issue by Technofied** [GeorgH93/MarriageMaster#152]
### Information
**Environment information**
*Plugin + server version info*:
2.2.2-SNAPSHOT-Release
Server: git-paper-101 (MC 1.16.1)
Java: 1.8.0_242
PlaceholderAPI: 

*Online mode*: Tes

*BungeeCord*: No

**Server/crash log**
>.... [08:09:37 INFO]: Technofied issued server command: /marry divorce SimplyMadi
>.... [08:09:37 WARN]: [MarriageMaster] Unhandled exception executing command 'marry' in plugin MarriageMaster v2.2.2-SNAPSHOT-Release
>.... [08:09:37 WARN]: java.lang.NullPointerException
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Management.MarriageManager.marryOnlineTest(MarriageManager.java:335)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Management.MarriageManager.divorce(MarriageManager.java:751)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Management.MarriageManager.divorce(MarriageManager.java:44)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.MarryDivorceCommand.execute(MarryDivorceCommand.java:73)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.MarryDivorceCommand.execute(MarryDivorceCommand.java:36)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:149)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:35)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:177)
>.... [08:09:37 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:143)
>.... [08:09:37 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [08:09:37 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
>.... [08:09:37 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [08:09:37 WARN]: at java.lang.Thread.run(Thread.java:748)

```

**Plugin config (optional)** Not included.

### Details
**Description**  
<!-- Replace this with a brief summary of the bug. -->
I cannot divorce players as it shows 
<img width="429" alt="Screen Shot 2020-07-25 at 2 13 34 pm" src="https://user-images.githubusercontent.com/40795318/88450372-0fd5e300-ce81-11ea-88e9-c4a191250965.png">

**Steps to reproduce**  
Marry a player
Try to divorce a player by doing /marry divorce 

**Expected behavior**  
<!-- Replace this with what you expect to happen. -->
The players get divorced
**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
<!-- Replace this with any additional information, if necessary. -->

**Comment by Technofied** [comment]
<img width="429" alt="Screen Shot 2020-07-25 at 2 13 34 pm" src="https://user-images.githubusercontent.com/40795318/88450398-385ddd00-ce81-11ea-82f7-fe1a1b762aa4.png">

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/208/artifact/artifacts/MarriageMaster-2.2.2-SNAPSHOT-Release.jar).

**Comment by Technofied** [comment]
> Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/208/artifact/artifacts/MarriageMaster-2.2.2-SNAPSHOT-Release.jar).

That seems to have fixed it, thank you!
