### ISSUE TITLE
A way to change player uuid/names from mysq database?

### ISSUE THREAD

**Issue by Malachiel87** [GeorgH93/MarriageMaster#153]
Hi, basicaly i have a external plugin that replace old uuid/name with new ones, but if i try to edit the marriage master tables, it don't affect the data, and it will be replaced again with the old values after the restart, any solution or api for allow to  do that? Thank you man :3

**Comment by GeorgH93** [comment]
Hi,

you should be able to just replace the UUID in the database (as long as it is properly formatted, if it is not properly formatted or null, the plugin will try to fix the UUID based on the players name by either querying Mojangs API or generating an offline mode UUID (when your server is running in offline mode/UUID_Type is set to offline)).
The player name will be updated every time a player joins if the current name does not match the stored name.
For unmarried players the changes should be available instantly. For married players you will have to reload the plugin (or at least the database, [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/212/artifact/artifacts/MarriageMaster-2.2.2-SNAPSHOT-Release.jar) allows you to reload only the database with `/marry reload database` (on Bukkit/Spigot/Paper servers (BungeeCord still needs to be restarted to reload the database)). 

If you still have problems with it, please provide me with more detailed information on what your plugin is doing when replacing the UUID and the configuration of your server (server type, output of `/marry version`, weather you are using BungeeCord or not, ...).
