### ISSUE TITLE
Cannot divorce.

### ISSUE THREAD

**Issue by Hmotak** [GeorgH93/MarriageMaster#154]
Hey, MarriageMaster works great for our server, but we discovered that noone can divorce.. Noone apparently has the permission. I watched a few videos and it seemed to work fine for them, i figured i did something wrong but dunno what. Is it something i have to change in config? thnaks

**Comment by GeorgH93** [comment]
Hey

Any priest should be able to divorce any couple (excluding them-self, if a priest is married, an other priest will have to divorce them). They can be set with either the `/marry setpriest` command or the `marry.priest` permission. (Command `/marry divorce <playername>`)

Additionally if you have set the `DivorceRequiresPriest` config option to `false` (or to `auto` and the `RequirePriest` option to `false`) all players that have the `marry.selfdivorce` permission will be able to divorce their partners by them self. (Command `/marry divorce`)

If the partner is offline the player performing the divorce will need the `marry.offlinedivorce` permission.

I hope this helps you to divorce players on your server.
