### ISSUE TITLE
/marry chat exposes vanished players

### ISSUE THREAD

**Issue by piotrskibapl** [GeorgH93/MarriageMaster#157]
### Information
**Environment information**
*Plugin + server version info*:

```

##### Start Marriage Master version info #####
Marriage Master: 2.2.4-Release
Server: git-Paper-385 (MC: 1.15.2)
Java: 1.8.0_121
Vault: 1.7.3-b131
PlaceholderAPI: 2.10.9
##### End Marriage Master version info #####

```

*Online mode*: no

*BungeeCord*: yes

### Details
**Description**  
The "/marry chat" allows players to see vanished players online by checking the tab completions.

**Steps to reproduce**  
1. Log in on the server while there's another vanished player online
2. Type "/marry chat " and scroll down until you see the other players name

**Expected behavior**  
All vanished players should be removed from tab completions for players that can't see them.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
The server is running the SuperVanish plugin (v 6.1.8)

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/227/artifact/artifacts/MarriageMaster-2.2.5-SNAPSHOT-Release.jar).

**Comment by piotrskibapl** [comment]
Just checked and it's working great now.
Thanks for your fast response!
