### ISSUE TITLE
Bungeecord

### ISSUE THREAD

**Issue by XipsAhoy** [GeorgH93/MarriageMaster#163]
If I have the plugin on my proxy and I enable bungeecord do I need mysql? And do I need to install on the other servers that are not the proxy?

**Comment by GeorgH93** [comment]
Yes, all servers need to use the same MySQL database and same database settings. It's also recommended to set all the other config options to match each other. You will have to put the plugin on all servers that should be able to use the plugin. Only chat home and tp are handled by the proxy.

**Comment by XipsAhoy** [comment]
Okay. I am gonna close this when I check if everything is working correctly!
