### ISSUE TITLE
The marry home viewing direction will be reset after a server restart

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#165]
The viewing direction from marry home is reset after a server restart.

Steps to reproduce:
1. Set a marry home with the viewing angle facing north.
2. Try the marry home -> the viewing direction will be correct.
3. Restart the server and use the marry home: The viewing direction has been reset and you will look south after the teleport.

MarriageMaster 2.2.9-SNAPSHOT-Release build 245
Paper 1.16.3 - 223

**Comment by GeorgH93** [comment]
Please try if [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/246/artifact/artifacts/MarriageMaster-2.2.9-SNAPSHOT-Release.jar) resolves the problem for you.

**Comment by TheoRetisch1** [comment]
Sorry for the delay! The provided build works fine, thank you for very much 💯
