### ISSUE TITLE
LuckPerms compatibility

### ISSUE THREAD

**Issue by Brokkonaut** [GeorgH93/MarriageMaster#172]
Latest versions of the LuckPerms plugin replace the MySql connector in Spigot to update it to a recent build. In that version MarriageMaster does no longer start, it just says "Unsupported database backend".

I think this happens because connection.getMetaData().getDatabaseProductName() now returns "MariaDB" instead of "MySQL".

It would be great if MarriageMaster could accept that backend too. ( https://github.com/GeorgH93/PCGF_PluginLib/blob/master/pcgf_pluginlib-common/src/at/pcgamingfreaks/Database/DBTools.java#L59 )

**Comment by GeorgH93** [comment]
Please try if adding [this](https://ci.pcgamingfreaks.at/job/PluginLib/455/artifact/target/PCGF_PluginLib-1.0.30-SNAPSHOT.jar) to your plugins solves the problem for you.

**Comment by Brokkonaut** [comment]
Thanks, this works 👍
