### ISSUE TITLE
Placeholder Issues

### ISSUE THREAD

**Issue by CyberSheppie** [GeorgH93/MarriageMaster#174]
### Help request

**Problem**
Can't get the placeholder hearts to appear in chat. We are running the following plugins:
- Marriage Master(Latest version as of submitting this)
- VentureChat
- Placeholder API

Other plugins of note:
- Vault
- LuckPerms

PlaceholderAPI has the extension for MarriageMaster enabled, so that shouldn't be the problem, and I'm stumped on what to do.

**What I have tried**
I have tried changing the prefix in the MarriageMaster Config to every variation of hearts to try to make it work, with no result. That's why I'm contacting you here, hoping to get some help getting this resolved.

Config File as it is right now:
https://pastebin.com/19RVgiyJ

**Comment by SrBedrock** [comment]
@CyberSheppie use {marriagemaster_heart} as placeholder on venturechat config.yml

**Comment by CyberSheppie** [comment]
> @CyberSheppie use {marriagemaster_heart} as placeholder on venturechat config.yml

That seems to have worked! Had hoped I could use the Magic Heart, but that just appeared white. 
What was strange though was that when I added the placeholder in Venturechat's config, the prefix from the Marriage Master config also appeared, so I have no idea what's up with that. 
But it works mostly as I want it, so thanks for the help!

**Comment by SrBedrock** [comment]
> Had hoped I could use the Magic Heart
@CyberSheppie https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders
Use {marriagemaster_magicheart}
