### ISSUE TITLE
Admin commands

### ISSUE THREAD

**Issue by austv** [GeorgH93/MarriageMaster#175]
**Problem**
I made some changes to my server and some users changed their uuid. Now, players who were married are no longer but in the / marry list their name continues. Anyway, I can solve this problem manually by divorcing and remarrying them. But I can't find a command here to automatically divorce and marry a couple without needing their online players or their commands (/marry accept). How do I do that?

**Comment by GeorgH93** [comment]
You can divorce them via the console without your players having to confirm it.
