### ISSUE TITLE
/Marry Gift BUG with ProCosmetics Plugin

### ISSUE THREAD

**Issue by BboyZeroOne** [GeorgH93/MarriageMaster#177]
### Information
**Environment information**
*Plugin + server version info*:

##### Start Marriage Master version info #####
Marriage Master: 2.2.11-Release
Server: git-Paper-267 (MC: 1.16.4)
Java: 1.8.0_191
MVdWPlaceholderAPI: 3.1.1
PlaceholderAPI: 2.10.9
#####  End Marriage Master version info  #####

*Online mode*: 
NO

*BungeeCord*:
YES

**Server/crash log**
NO

**Plugin config (optional)**
NOT REQUIRED

### Details
**Description**  
When a player opens up ProCosmetic GUI, they could "/marry gift" the selector item to their partner.
https://user-images.githubusercontent.com/51330952/102966849-b0f9c000-452b-11eb-85ba-b56dcbdb1708.mp4

**Steps to reproduce**  
1. Open ProCosmetic GUI menu with /pc open main
2. Select the item u wana use
3. Select the item on your hotbar and do /marry gift to your partner
4. Bug achieved.

**Expected behavior**  
Should not be able to execute this command on this item/nbt

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
This happened with CMI's /hat, and it was fixed. I believe it could be fixed on your side too.
https://github.com/Zrips/CMI/issues/4772

If you require the plugin for testing, please do add me on discord so I can share it with you with the permission from the dev.
Discord ID: BboyZeroOne#6251

**Comment by GeorgH93** [comment]
v2.3 added the option to filter items that can be gifted.
