### ISSUE TITLE
Marry home resets after server restart

### ISSUE THREAD

**Issue by jordanwilliams1** [GeorgH93/MarriageMaster#178]
Not much to say, After a server reload your /marry home gets deleted

**Comment by GeorgH93** [comment]
Are you using Multiverse? If so please download [v2.2.12](https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.2.12).

**Comment by jordanwilliams1** [comment]
@GeorgH93 Thanks that fixed the issue 👍
