### ISSUE TITLE
Latest Update Question - Uranium

### ISSUE THREAD

**Issue by Midnight9746** [GeorgH93/MarriageMaster#18]
What on Earth is the "urainum support"?

I googled and googled and don't see anything on the matter. Is it marrying more than one or what?

**Comment by GeorgH93** [comment]
Uranium is a cauldron (bukkit server with mod support) fork: https://git.aimc.vip/UraniumDev/Uranium
It's quite popular in china.

**Comment by Midnight9746** [comment]
OHHH... lol I thought it meant that players could marry random things... like the a diamond block XD
