### ISSUE TITLE
Polish item translation

### ISSUE THREAD

**Issue by szumielxd** [GeorgH93/MarriageMaster#180]
I've made a polish items translation for MarriageMaster.
I think it could be added to next release.

Link: https://hastebin.com/niwiziqove.yaml

**Comment by GeorgH93** [comment]
I am sorry, but the link is not working for me.

**Comment by szumielxd** [comment]
So here you have another one:
https://pastebin.com/50eFNpgu

**Comment by GeorgH93** [comment]
Thanks, they will be included in the next update.
