### ISSUE TITLE
Please add a Space after Heart

### ISSUE THREAD

**Issue by JHiroshige** [GeorgH93/MarriageMaster#181]
Can you add a Space in the placeholder for this one %marriagemaster_heart%
Because when I add a space after the papi, every unmarried player has a wierd space before his name which I wanna avoid
Thanks

**Comment by GeorgH93** [comment]
You can change how the placeholders are formatted in the language file.
You can change the Placehoders.Heart.Married value like this:
```
Placeholders:
  Heart:
    Married: "&c<heart>&f "
```
