### ISSUE TITLE
The /accept command is taking the server down.

### ISSUE THREAD

**Issue by Zireaphus** [GeorgH93/MarriageMaster#182]
### Information
**Environment information**

```
Marriage Master: 2.2.13-Release
MC 1.16.5
```

*Online mode*: "no"

*BungeeCord*: "no"

**Server/crash log**

```
https://pastebin.com/snmycDUE
```

**Plugin config (optional)**

```

https://pastebin.com/x6GjKRKU

```

### Details
**Description**  
Every time a player performs the /accept command, the server crashes. I can only get married through the Console.

**Steps to reproduce**  
1 - Two players who want to get married;
2 - A priest available;
3 - The priest types /marry <player> <player>;
4 - The priest presses enter;
5 - One of the players who wants to get married types /accept.

**Expected behavior**  
They are expected to get married without the server going down.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Which version of UltimateChat are you using?

**Comment by Zireaphus** [comment]
UltimateChat-1.9.1-b265-Universal.jar.

**Comment by GeorgH93** [comment]
It should work with the newest version of UltimateChat you can find it on their build server [here](http://host.areaz12server.net.br:8081/job/UltimateChat/289/).

**Comment by Zireaphus** [comment]
Worked perfectly! Thank you.
