### ISSUE TITLE
Question about giving commands

### ISSUE THREAD

**Issue by foxinnit** [GeorgH93/MarriageMaster#185]
### Help request

**Problem**

The commands to give permission doesn't seem to work or it doesn't recognize it. I don't understand how to give permission with the /marry.*
**What I have tried**

Tried to look for it in the config and used the console.

**Comment by GeorgH93** [comment]
To give permissions you need a permissions plugin.
If you do not have a permission plugin you can use the [permissions.yml](https://bukkit.gamepedia.com/Permissions.yml) file in some limited capacity.
