### ISSUE TITLE
Don't know how to turn {} into a Component - ERROR

### ISSUE THREAD

**Issue by Aides123** [GeorgH93/MarriageMaster#188]
Message file: https://pastebin.com/L2JA2drX
Error: https://pastebin.com/b27w4SR2
Plugin version: 2.3
Server version: 1.16.5

Desc:
The plugin does not process an empty line from "". After adding this, I get an error in the console while using the command

          - "&2&lZWIĄZEK - LISTA KOMEND DLA GRACZA"
          - ""    <-- THIS
          - "&2* &a/slub lista &8- &fLista wszystkich związków"

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/267/artifact/artifacts/MarriageMaster-2.3-Release.jar).

**Comment by Aides123** [comment]
Thanks
