### ISSUE TITLE
Offline mode support

### ISSUE THREAD

**Issue by Artuto** [GeorgH93/MarriageMaster#19]
Hi, when a no premium player marries they doesnt have a partner. Any way to fix this?

**Comment by ArtutoGamer** [comment]
bump

**Comment by GeorgH93** [comment]
Hi, if you are running an offline mode server you should make sure that the "UseUUIDs" option is disabled for best reliability. Also please check your log for errors.

**Comment by ArtutoGamer** [comment]
I've set UseUUIDs to false and still...

**Comment by ArtutoGamer** [comment]
bump?

**Comment by GeorgH93** [comment]
Sorry for the slow answers, I don't have much time at the moment. Can you please give me more details.
Are there any errors in the log?
Are the players listed with the "/marry list" command?
Have the players been married by a priest or on their own?
Are you using Files or MySQL as database type?
Which version of the plugin are you using?
Which mc server software are you using and whats it's version?

**Comment by ArtutoGamer** [comment]
No errors
Married players: https://cdn.discordapp.com/attachments/323954859713888256/403303235407970308/Capture_2018-01-17-15-40-07.png
By an OP (myself)
MySQL
https://cdn.discordapp.com/attachments/323954859713888256/403303729186603038/Capture_2018-01-17-15-44-54.png
https://cdn.discordapp.com/attachments/323954859713888256/403303729186603038/Capture_2018-01-17-15-44-54.png

**Comment by GeorgH93** [comment]
Which plugin are you using for the aliases?

**Comment by ArtutoGamer** [comment]
If you mean Player's nicknames, EssentialsX

**Comment by ArtutoGamer** [comment]
bump

**Comment by ArtutoGamer** [comment]
any news?

**Comment by GeorgH93** [comment]
I am sorry. I wasn't able to reproduce the error.
If you aren't using BungeeCord I would like to ask you to try if the V2.0 beta works for you (it's an entire rewrite of the plugin): https://www.spigotmc.org/threads/marriage-master-mc-1-7-1-12.127262/page-7#post-2112770

**Comment by ArtutoGamer** [comment]
Maybe if you could send the right configuration here? So i can take a look and check if is my fault (probably/10)

**Comment by GeorgH93** [comment]
Since the plugin detects you as married at least once after you have married, your setup should be fine and working. However there seem to be some problem with the database as the results seems to be not reliable, but I have no idea what would cause that.
