### ISSUE TITLE
receiving in creative

### ISSUE THREAD

**Issue by 100petr** [GeorgH93/MarriageMaster#192]
### Feature request

**Feature description**

The AllowInCreative function is already in the configuration, but receiving in creative (sending gift to players who are already in creative) no 
**How the feature is useful**

Players would not be able to share items from survival to creative.

**Comment by GeorgH93** [comment]
Option added with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/lastSuccessfulBuild/artifact/artifacts/MarriageMaster-2.4-RC2-Release.jar).
