### ISSUE TITLE
mysql connection of servers does not sync/fail

### ISSUE THREAD

**Issue by hkkongou** [GeorgH93/MarriageMaster#196]
### Help request

**Problem**

hi, i have connected 3 server using mysql, these server are linked with bungeecord online mode true, and i have set up the config .yml with bungeecord mode and uuid.

let the servers as a,b,c
problem 1 is that, when i marry in server c, then i go server a, it say i haven't got married
problem 2 is that, some other players have married when using sqlite format, and after converted into mysql, when they got online, the system say the people did not marry despite the mysql database have marry data.

**What I have tried**

i have tried to read the wiki for multiple times , i have also asked in previous ticket before convert into mysql, things should be thing but still, not good : (

config.yml
https://gist.github.com/hkkongou/08b0bc5ef26c670d23cbc96108f735c5

i have set up the ServerName: correctly, which is different each server 🤔

**Comment by GeorgH93** [comment]
Please also add the plugin to your BungeeCord server.

**Comment by hkkongou** [comment]
> Please also add the plugin to your BungeeCord server.
> For the missing marriages I would recommend to remarry them by hand.

sorry, do you mean adding the marriagemaster plugin to bungeecord plugin folder?
(sorry my english not good

**Comment by GeorgH93** [comment]
Yes, I do. And then make sure to set the correct MySQL credentials there too.

**Comment by hkkongou** [comment]
> Yes, I do. And then make sure to set the correct MySQL credentials there too.

sorry i still have some questions...
my bungeecord is true 
should i use ``UseUUIDSeparators: true`` and  ``UUID_Type: offline``?
the bungeecord online mode is true but the backend server is false because thats how it should set, but if you say according to bungeecord setting, so is the bungeecord itself or the backend bungeecord server 🤔🤔🤔

not understand : (

**Comment by GeorgH93** [comment]
UseUUIDSeparators does not matter, but must be the same on all servers.

UUID_Type should be online

**Comment by hkkongou** [comment]
> UseUUIDSeparators does not matter, but must be the same on all servers.
> 
> UUID_Type should be online

i believe i have already set up bungeecord, and the backend server correctly.
i tested marry using 2 account, but after i use /marry reload in one server, the server will then say i am not married, what should i do?

**Comment by GeorgH93** [comment]
Sounds like there is something wrong with your database settings.
Could you please share your log file.

**Comment by hkkongou** [comment]
> Sounds like there is something wrong with your database settings.
> Could you please share your log file.

Which log should I provide?
The server one or the bungeecord one ? Or both ?

**Comment by GeorgH93** [comment]
The server one please.

**Comment by hkkongou** [comment]
> The server one please.

sure, this is
https://gist.github.com/hkkongou/eb6102074c637b99fb3448f0536b6794

**Comment by hkkongou** [comment]
> Looks like there is bad data in your marriage table and that is preventing the plugin form loading the marriages.
> Please try to run this query `` SQL UPDATE marry_partners SET `date`=DEFAULT WHERE `date`=0; `` on your database.

it worked, thank you so much!
