### ISSUE TITLE
Marry sethomes are getting cleared after every server restart

### ISSUE THREAD

**Issue by cloakfox** [GeorgH93/MarriageMaster#202]
Marry sethomes made in other worlds seem to be getting cleared after every server restart.
Players set their marry home on their island world (bentobox)

Not using MultiVerse (noticed users reporting same issues in previous reports where using MultiVerse)

No errors on startup.

Using version: 2.4.1-Release
Paper 1.16.5
Java 8

**Comment by GeorgH93** [comment]
Please try if [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/lastSuccessfulBuild/artifact/artifacts/MarriageMaster-2.4.3-RC2-Release.jar) solves the issue for you.
