### ISSUE TITLE
Teleporting to partner in negative layers doesn't work

### ISSUE THREAD

**Issue by thiagogebrim13** [GeorgH93/MarriageMaster#204]
### Information
**Environment information**
*Plugin + server version info*:
```

Plugin: 2.4.1 Server: 1.17

```

*Online mode*: yes

*BungeeCord*: yes

**Server/crash log**

```

No

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Teleporting to partner in negative layers doesn't work

**Steps to reproduce**  
I use / match tp and it doesn't work if my partner is on a negative layer

**Expected behavior**  
was to teleport

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Do you mean y < 0? You can disable that and all other safety checks with the `CheckSafety` config option.

**Comment by thiagogebrim13** [comment]
I wanted to keep it safe, I use a datapack that has new negative caves and even though it's safe you can't go there

**Comment by GeorgH93** [comment]
I see. Could you please share this datapack with me so that I can test (and fix) this.

**Comment by thiagogebrim13** [comment]
https://www.planetminecraft.com/blog/how-to-download-and-play-the-official-minecraft-1-17-caves-and-cliffs-update-data-pack/

**Comment by GeorgH93** [comment]
Thanks, should work with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/lastSuccessfulBuild/artifact/artifacts/MarriageMaster-2.4.2-RC2-Release.jar).
