### ISSUE TITLE
Marriage Master exception 

### ISSUE THREAD

**Issue by darkdragon0226** [GeorgH93/MarriageMaster#205]
Hi, when i use /marry gift I get this error
https://gist.github.com/darkdragon0226/7b365e83f0dbbaf19b3c408cd861ef37

Plugin: Marriage Master 
Version:  paper-1.17-68
 ##### Start Marriage Master version info #####
Marriage Master: 2.4.1-Release
Server: git-Paper-68 (MC: 1.17)
Java: 16.0.1
PlaceholderAPI: 2.10.9
 #####  End Marriage Master version info  #####

**Comment by GeorgH93** [comment]
Should be fixed in [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/296/artifact/artifacts/MarriageMaster-2.4.2-RC2-Release.jar).
