### ISSUE TITLE
Add Korean translation (there is a file)

### ISSUE THREAD

**Issue by happykrcheese** [GeorgH93/MarriageMaster#209]
### Feature request

**Feature description**

Hello. I just finished the korean translation of the plugin, but I don't know how to contribute to this project, so I'm just posting the link here. Please add this to MarriageMaster/resources/lang folder : [https://github.com/happykrcheese/MarriageMaster_KoreanTranslation/blob/dev/MarriageMaster/resources/lang/ko.yml](url)

**How the feature is useful**

Adds korean translation for korean users/server admin/server owners.

**Comment by GeorgH93** [comment]
Thanks for sharing. I have added it.

For the future, if you click on the `Fork` button on the top right GitHub will create a copy of the repository on your account, which you can than modify and create pull requests from, to bring your changes back into the upstream repository.
