### ISSUE TITLE
had something to ask

### ISSUE THREAD

**Issue by greensabob** [GeorgH93/MarriageMaster#21]
is there away i can make it so when players do /marry divorce it just divorces them with out the other player needing to to accept? this way if a player stop playing then the other player can move on or if they just want to marry some one new and the other player is being a butt they can just end it them self?

**Comment by GeorgH93** [comment]
You could use the "AllowSelfDivorce" option to allow players to divorce without a priest.
The "marry.offlinedivorce" permission can be used to allow priests or players to divorce when one of the couple is offline.
