### ISSUE TITLE
Plugin Compile Error Against API

### ISSUE THREAD

**Issue by silverwolfg11** [GeorgH93/MarriageMaster#211]
### Details
**Description**  

Hello, I am trying to use the MarriageMaster API in a custom plugin, however, when I compile my plugin, I get compile errors caused by the MarriageMaster API.

My plugin uses maven, and the `MarriageMaster-API-Bukkit` dependency (version 2.4). 

The error I get when compiling is `cannot access at.pcgamingfreaks.Bukkit.Message.IMessage`. The error is at a line that utilizes `MarriagePlayer#getUUID()`.

My best guess is that the API does not shade in everything and is missing the `at.pcgamingfreaks.Bukkit.Message.IMessage` class. So when the compiler tries to link against that class, it cannot resolve all the appropriate information.

**Steps to reproduce**  

Create a maven project and use the `MarriageMaster-API-Bukkit`  version `2.4` dependency. Create a class or method that utilizes `MarriagePlayer` and attempt to compile the new project. Compilation will fail.

**Expected behavior**  

Compilation does not fail, and the plugin compiles fine.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by silverwolfg11** [comment]
Ah I missed another issue regarding the same error. I will close this for now. Please preferably update the API README while you fix the issue with the API.

**Comment by silverwolfg11** [comment]
Reopening this issue because using `MarriageMaster-API` version `2.3.1` compiles, but cannot be casted to the correct `MarriagePlugin` during runtime. Specifically `at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster cannot be casted to at.pcgamingfreaks.MarriageMaster.Bukkit.API.MarriageMasterPlugin`.  

Using `MarriageMaster v2.4.1-Release` on my test server and it starts in `Standalone` mode.

**Comment by GeorgH93** [comment]
Should be fixed with [v2.4.2](https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.4.2).
