### ISSUE TITLE
No permission issue: unable to use /marry home, /marry tp, and /marry chat

### ISSUE THREAD

**Issue by jahua50** [GeorgH93/MarriageMaster#216]
### Information
**Environment information**
*Plugin + server version info*:
paper 1.17.1, marriage 2.4.2
```

[image](https://user-images.githubusercontent.com/35772634/130142038-29e2eb5e-4386-45dc-bd11-97b36d7a199e.png)

```

*Online mode*: Yes.

*BungeeCord*: Yes.

**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
I use luckperms and marriage master on bungeecord, both uses mysql remote database. I gave users marry.user, but they are not able to use /marry home, /marry tp, and /marry chat in game. No console outputs. It said that "you don't have permission to do that". But they can marry, list and do other commands.  I tried the alias method on bungeecord, but it doesn't work.

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by jahua50** [comment]
Sorry but I really dont know how to use the format thing above. I use luckperms and marriage master on bungeecord, both uses mysql remote database. I gave users marry.user, but they are not able to use /marry home, /marry tp, and /marry chat in game. No console outputs. It said that "you don't have permission to do that". But they can marry, list and do other commands.  I tried the alias method on bungeecord, but it doesn't work
Im using paper 1.17.1 and marriage 2.4.2

**Comment by GeorgH93** [comment]
I checked, the permission group definition is indeed missing for bungeecord. I will add it with the next update.
Until then, you can add the following permissions yourself: `marry.tp`, `marry.home`, `marry.chat`, `marry.chat.format`, `marry.chat.color`

**Comment by jahua50** [comment]
> I checked, the permission group definition is indeed missing for bungeecord. I will add it with the next update.
> Until then, you can add the following permissions yourself: `marry.tp`, `marry.home`, `marry.chat`, `marry.chat.format`, `marry.chat.color`

Thank you so much for the help!
