### ISSUE TITLE
Can`t find at.pcgamingfreaks.Command.HelpData class/interface

### ISSUE THREAD

**Issue by Blaxor** [GeorgH93/MarriageMaster#218]
### Help request

**Problem**
i try to extend the MarryCommand class to make a subcommand 
![image](https://user-images.githubusercontent.com/10373410/130292136-5b878902-91df-4339-8adf-c33d7bfd4999.png)

**What I have tried**

https://gist.github.com/Blaxor/91a856b25638b29fd873965463079713 <- this is the normal dependency 
I try to add the release version 2.4.2 as system lib in pom but the same problem. So if you can help me. let me know!

**Comment by GeorgH93** [comment]
The command API is currently only not available in standalone mode.
You additionally need [this library](https://github.com/GeorgH93/PCGF_PluginLib).
The library also must be installed on the server to use the commands API of Marriage Master.

You can check if the commands API is available by checking the `MarriageMasterPlugin.isRunningInStandaloneMode()` method. If it returns true the dependencies needed for the commands API are not available.
