### ISSUE TITLE
/marry tp -> Your partner is offline

### ISSUE THREAD

**Issue by MithrandirCraft** [GeorgH93/MarriageMaster#22]
So sometimes married players can't tp to each other with the error "Your partner is offline" even though the partner is clearly online.

I think I already reported the same/symilar issue. Though it's definetly improved since then, it's still randomly present and we get many complaints (crying).

A current situation features two players, A and B. B can teleport to A, but not A to B for some unknown reason, and the message is displayed.

MarriageMaster v 1.31.4
Spigot 1.12.2

**Comment by GeorgH93** [comment]
I will look into it, but I don't know if i will fix it for V1.x builds.
