### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by LucidAPs** [GeorgH93/MarriageMaster#223]
##### Start Marriage Master version info #####
 Marriage Master: 2.4.3-RC3-Release
Server: git-Purpur-1383 (MC: 1.17.1)
Java: 16.0.2
Minepacks: 2.4.2-Release
Vault: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
PlaceholderAPI: 2.10.10
#####  End Marriage Master version info  #####

Bungeecord offline mode

Huge spikes when using the marry command
![image](https://user-images.githubusercontent.com/42933023/132987729-d56dd85e-467c-4d90-a68e-aee9365ca90e.png)
is it doing sync io or something for lookups?

**Comment by GeorgH93** [comment]
Can you please share the full timings report with me?

**Comment by LucidAPs** [comment]
https://timings.pl3x.net/?id=a0a2c299f75c4cfaa38f6ae2c77013d6

**Comment by GeorgH93** [comment]
Just to confirm, this lagg spike happened after using the gift command? If so, do you by any chance know which item was sent through the gift command?

**Comment by LucidAPs** [comment]
You are right I found it in the logs, only one player used the gift command
[12:24:20] [Server thread/INFO]: AdisPadis issued server command: /marry gift
unfortunally I dont know the item used, I will try to contact the player and maybe he remembers
