### ISSUE TITLE
Gift command causing 4000ms lag spikes

### ISSUE THREAD

**Issue by iLemon** [GeorgH93/MarriageMaster#230]
### Information
**Environment information**
*Plugin + server version info*:

![image](https://user-images.githubusercontent.com/18317307/140924681-4e759751-3ac8-47f6-b3d6-f45ac79c909b.png)

*Online mode*: Yes

*BungeeCord*: No

**Server/crash log**
![image](https://user-images.githubusercontent.com/18317307/140924717-bc7909c2-ca35-47e8-8aee-2472a52a9f03.png)

**Comment by GeorgH93** [comment]
Thanks for the report. I probably should do more tests in standalone mode. :D
[This update](https://ci.pcgamingfreaks.at/job/MarriageMaster/320/artifact/artifacts/MarriageMaster-2.5.1-RC2-Release.jar) should fix it.
