### ISSUE TITLE
/Marry Home Error

### ISSUE THREAD

**Issue by ByNetsky** [GeorgH93/MarriageMaster#24]
User can't use this command, but I as Admin it works fine for me..

30.05 19:07:16 [Server] INFO PLAYERXY issued server command: /marry home
30.05 19:07:16 [Server] SEVERE null
30.05 19:07:16 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'marry' in plugin MarriageMaster v1.31.5
30.05 19:07:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
30.05 19:07:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
30.05 19:07:16 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:555)
30.05 19:07:16 [Server] INFO at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1390)
30.05 19:07:16 [Server] INFO at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1250)
30.05 19:07:16 [Server] INFO at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1176)
30.05 19:07:16 [Server] INFO at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:60)
30.05 19:07:16 [Server] INFO at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:442)
30.05 19:07:16 [Server] INFO at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:223)
30.05 19:07:16 [Server] INFO at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:53)
30.05 19:07:16 [Server] INFO at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
30.05 19:07:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
30.05 19:07:16 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
30.05 19:07:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
30.05 19:07:16 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
30.05 19:07:16 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
30.05 19:07:16 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getHealth()D
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Home.TPHome(Home.java:89)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Home.access$100(Home.java:28)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Home$2.onResult(Home.java:71)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Home$2.onResult(Home.java:63)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Databases.Files.GetHome(Files.java:488)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Databases.Files.GetMarryHome(Files.java:475)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.Home.TP(Home.java:62)
30.05 19:07:16 [Server] INFO at at.pcgamingfreaks.MarriageMaster.Bukkit.Listener.OnCommand.onCommand(OnCommand.java:287)
30.05 19:07:16 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.05 19:07:16 [Server] INFO ... 15 more

**Comment by GeorgH93** [comment]
The bug is caused by your very old version of Minecraft (1.5). Since the problem only affects old versions of Minecraft I will not fix the bug.
If you turn of the teleport delay the command will work for normal players too.
