### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [GeorgH93/MarriageMaster#241]
On build 364
https://nekobin.com/rorukuzesa
![image](https://user-images.githubusercontent.com/42933023/147367049-0372f2c0-3536-4aeb-8091-520fcd8a2599.png)

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/365/).

**Comment by LucidAPs** [comment]
Yeap fixed.
