### ISSUE TITLE
'/marry backpack' seems to be broken?

### ISSUE THREAD

**Issue by dro1d-89o** [GeorgH93/MarriageMaster#243]
### Information
**Environment information**
*Plugin + server version info*:

```

 ##### Start Marriage Master version info #####
Marriage Master: 2.5.5-SNAPSHOT-Standalone
Server: git-Paper-101 (MC: 1.18.1)
Java: 17.0.1
Minepacks: 2.4.3-Standalone
Vault: 1.7.3-b131
mcMMO: 2.1.206
#####  End Marriage Master version info  #####

```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**

```

no errors

```

**Plugin config (optional)**

```

[](https://gist.github.com/dro1d-89o/580de6b22bc270beebc78b89251cd72c)

```

### Details
**Description**  
Any /marry backpack command does not work. No errors, no messages in the chat just doesn't work.

**Steps to reproduce**  
/marry backpack, /marry backpack on/off

**Expected behavior**  
open the backpack of the partner

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
was unable to find a similar issue

**Comment by GeorgH93** [comment]
Please try if [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/365/artifact/artifacts/MarriageMaster-2.5.5-SNAPSHOT-Release.jar) solves the problem for you.

**Comment by dro1d-89o** [comment]
will check right now

**Comment by dro1d-89o** [comment]
Did not solve the problem, as there are no errors in the log nor the console i dont know whats going wrong so I cant even begin to help. ive recorded and attached a video in the hopes that it will help. Have a good Christmas day

https://user-images.githubusercontent.com/62203146/147389819-eaf3cf09-aa9c-476b-9ca7-accf5e160773.mp4

**Comment by GeorgH93** [comment]
I think [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/366/artifact/artifacts/MarriageMaster-2.5.5-SNAPSHOT-Release.jar) should fix it.

Sorry, I am on my notebook which is dying with one Minecraft instance already, so I can't do too much testing.

**Comment by dro1d-89o** [comment]
Awesome, this has fixed it! Thank you very much!
