### ISSUE TITLE
Cannot marry when economy option enable

### ISSUE THREAD

**Issue by JokerLiuPro** [GeorgH93/MarriageMaster#25]
MarriageMaster V2 (Build: 29)
git-paper-1428 (MC: 1.12.2)

Although it show  "You paid 150.00 Dollars for your marriage (xxx.xx Dollars left)"
but it still not married.
everything work fine when economy option is disable

**Comment by GeorgH93** [comment]
Should be fixed now: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/32/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar
