### ISSUE TITLE
MarriageMaster dev version bug

### ISSUE THREAD

**Issue by thiagogebrimm** [GeorgH93/MarriageMaster#255]
![image](https://user-images.githubusercontent.com/75040244/158232877-bb7d741e-6bde-4e5c-8dd5-53fe3b92b127.png)

**Comment by thiagogebrimm** [comment]
This is the default file generated by the plugin

**Comment by GeorgH93** [comment]
[This](https://ci.pcgamingfreaks.at/job/PluginLib/595/artifact/target/PCGF_PluginLib-1.0.36-SNAPSHOT.jar) might solve the issue.

**Comment by thiagogebrimm** [comment]
Solved
