### ISSUE TITLE
"You are not allowed to send gifts in your current game mode."

### ISSUE THREAD

**Issue by SaishoVibes** [GeorgH93/MarriageMaster#265]
### Information
**Environment information**
*Version 2.6.6, Paper 1.19*

*Online mode*: yes

*BungeeCord*: no

### Details
**Description**  
I have tried to do /marry gift and /marry give and it says "You are not allowed to send gifts in your current game mode." in chat. I have no clue what to do.

**Steps to reproduce**  
just went on the server, made sure my partner was online, and ran the command holding an item.

**Expected behavior**  
It should just give the item but it doesn't.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
Possibly remove a game mode requirement?

**Comment by SaishoVibes** [comment]
Actually for the love of god close this. I am sorry, but the server owner didn't add in the bypass gamemode permission.

**Comment by GeorgH93** [comment]
The issue has been resolved with the [v2.6.7 update](https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.6.7). Should work correctly again without the bypass permission.
