### ISSUE TITLE
"/marry seen" exposes vanished players

### ISSUE THREAD

**Issue by piotrskibapl** [GeorgH93/MarriageMaster#274]
### Information
**Environment information**
*Plugin + server version info*:

```

Marriage Master: 2.6.7-Release
Server: git-Paper-387 (MC: 1.18.2)
Java: 17.0.4.1
Vault: 1.7.3-b131
PlaceholderAPI: 2.11.2

```

*Online mode*: no

*BungeeCord*: yes

### Details
**Description**  
If your partner has access to vanish, "/marry seen" command exposes if the partner is online or not, even when vanished.

**Steps to reproduce**  
1. Join the server with two accounts and have a marry
2. Turn on vanish on one of these accounts, so that the other one can't see him online
3. Run "/marry seen" on the account that can't see the partner
4. The command output tells you that your partner is online

**Expected behavior**  
There should be a date displayed of when the partner was last online and not vanished.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
I'm using SuperVanish v6.2.12 for vanish purposes.

**Comment by SrBedrock** [comment]
@GeorgH93 you can close this.
