### ISSUE TITLE
Update 1.13 bungee

### ISSUE THREAD

**Issue by xPiston** [GeorgH93/MarriageMaster#29]
https://hastebin.com/egiyusurin.md
Spigot ver = spigot-1.13-R0.1-SNAPSHOT-b1779

**Comment by GeorgH93** [comment]
Thanks for the report.
This build should fix the problem: https://ci.pcgamingfreaks.at/job/MarriageMaster/60/artifact/target/MarriageMaster-1.31.7-SNAPSHOT.jar

**Comment by xPiston** [comment]
the / marry home does not work anymore
bunguee : https://hastebin.com/gukuyeyezo.php
spigot : https://hastebin.com/alaqugotig.makefile

**Comment by GeorgH93** [comment]
This build should fix it: https://ci.pcgamingfreaks.at/job/MarriageMaster/61/artifact/target/MarriageMaster-1.31.7-SNAPSHOT.jar

**Comment by xPiston** [comment]
Perfect your new version works perfectly
