### ISSUE TITLE
Action_bar Messages not showing up

### ISSUE THREAD

**Issue by AnAnthem** [GeorgH93/MarriageMaster#291]
Action bar messages from the kiss/hug are not showing up.

Tried it on the latest spiggot / paper both 1.19.3
Removed all plugins except marriage master, still the same issue

**Comment by GeorgH93** [comment]
Fixed with [2.6.12 release](https://github.com/GeorgH93/MarriageMaster/releases/download/v2.6.12/MarriageMaster-2.6.12-Release.jar).
