### ISSUE TITLE
Commands aren't working / permission issue on latest version

### ISSUE THREAD

**Issue by iLemon** [GeorgH93/MarriageMaster#292]
Using MarriageMaster 2.6.13

<img width="616" alt="CleanShot 2023-03-20 at 16 24 39@2x" src="https://user-images.githubusercontent.com/18317307/226404795-0906b4d4-6f1a-4eb0-a9c1-d179445174ca.png">
<img width="627" alt="CleanShot 2023-03-20 at 16 24 52@2x" src="https://user-images.githubusercontent.com/18317307/226404863-dab27302-685e-46e1-85de-a18d3b21374e.png">

Since a recent update, players have no access to marry commands despite having marry.user.

**Comment by iLemon** [comment]
![image](https://user-images.githubusercontent.com/18317307/226410006-02fd83e6-dd01-445f-a331-0625f2929fcf.png)

**Comment by GeorgH93** [comment]
More fun with the new paper plugins. :|

Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/466/artifact/artifacts/MarriageMaster-2.6.14-SNAPSHOT-Release.jar).

**Comment by iLemon** [comment]
Seems good now!
