### ISSUE TITLE
multiple marry partner if they got permission

### ISSUE THREAD

**Issue by wolfawwent** [GeorgH93/MarriageMaster#309]
### Feature request

**Feature description**
 
player can marry more than 2 player if they have permission

**How the feature is useful**
 
for server owner 
i want to make many religion in my server
and some of them are heresy . i want those specific player can marry more than 1

**Comment by SrBedrock** [comment]
@GeorgH93 you can close https://github.com/GeorgH93/MarriageMaster/commit/853410cf66ee61eb680168f385e9131f4f42e159
