### ISSUE TITLE
Question about V2.

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#31]
We can't marry players. It says that we must do /marry marry player1 player2 but it doesn't work.

Could you explain to me how to marry players ?

**Comment by GeorgH93** [comment]
You can only marry on your own if the option "Marriage.RequirePriest" is set to false. However then everyone would be able to marry on their own. Even if you are a priest you cannot marry yourself with an other player, unless the option is disabled.

**Comment by TheIntelloBox** [comment]
If I do /marry marry TheIntelloBox player2 with "Marriage.RequirePriest" set to false, it says "you don't have permission to do that".
