### ISSUE TITLE
Translate problem

### ISSUE THREAD

**Issue by QuestionCatcher** [GeorgH93/MarriageMaster#319]
### Help request

**Problem**

Problem with translating to Polish language

**What I have tried**

I translate line by line to polish language. I checked text format(proper tabs spaces, etc.)

Translate link:
https://gist.github.com/QuestionCatcher/5755f6a2f7415a090ee0391c850f0dbe

Console warn:
https://gist.github.com/QuestionCatcher/af9a29474bf56f3e7263ee8a3fea5654

**Comment by GeorgH93** [comment]
There is something wrong with the indentations in your file.
Corrected version:
[po.yml](https://github.com/GeorgH93/MarriageMaster/files/13690119/po.txt)
