### ISSUE TITLE
question for marry chat

### ISSUE THREAD

**Issue by MerlinK11** [GeorgH93/MarriageMaster#34]
hi i have a question for marry chat i want to spy the chat for prevent Ads and bad words ! it is possible?

**Comment by GeorgH93** [comment]
hi, you can use "/marry listenchat" to see what your players are writing.

**Comment by NekoShouta** [comment]
Is there a possibility to save the spy option, although the moderator leaves and joins the server?

**Comment by GeorgH93** [comment]
Not in Marriage Master V1.X, V2.0 has a permission to automatically listen on the chat.
Until the release of V2.0 you can use something like the [Macro / Keybind Mod](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1275039-macro-keybind-mod).

**Comment by MerlinK11** [comment]
that is probably for v2.0 how you do to realese the V 2.0
????
