### ISSUE TITLE
Error occur while migrating file

### ISSUE THREAD

**Issue by momoservertw** [GeorgH93/MarriageMaster#37]
Please help me :(

This is the error message.
https://pastebin.com/zSDyaDnv

MarriageMaster_FilesToMySQLConverter-1.0-SNAPSHOT

**Comment by GeorgH93** [comment]
What is your MySQL server version?

**Comment by momoservertw** [comment]
MySQL Community server - GPL
Version 8.0.12

**Comment by momoservertw** [comment]
Still has error message.
https://pastebin.com/NEbtDACz

I set the Properties: ["useSSL=false"]

**Comment by GeorgH93** [comment]
I am sorry for the inconvenience, the tool never was used much and has not been update in a long time.
This version should handle the connection properties settings correctly: https://ci.pcgamingfreaks.at/job/MarriageMaster%20FilesToMySQLConverter/8/artifact/target/MarriageMaster_FilesToMySQLConverter-1.0-SNAPSHOT.jar

**Comment by GeorgH93** [comment]
It seems that the time zone on the server is not set, have never encountered that before, maybe they have chanced the default behavior, I will test that.
It should work when you add the serverTimezone connection property like that: `Properties: ["useSSL=false", "serverTimezone=UTC"]`
It's possible that you will also need that parameter to use the plugin with MySQL.

**Comment by momoservertw** [comment]
Wow
The migration is successful and there are no errors.
Thank you very much :)
