### ISSUE TITLE
Marriage Master V.2 1.13.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#39]
Hello ! 🗡 

Error: https://hastebin.com/aqobaxarig.md

Thanks a lot for fixing it ! :D
TheIntelloBox. :D

**Comment by GeorgH93** [comment]
Hello,

Please update the PluginLib: https://ci.pcgamingfreaks.at/job/PluginLib/214/artifact/target/PluginLib-1.0.6-SNAPSHOT.jar
This should fix the crash, for the other error I will add an workaround soon.

Best regards
Georg

**Comment by GeorgH93** [comment]
This build should also fix the "constraint failed" error:
https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/40/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by TheIntelloBox** [comment]
I believe it's fixed, thanks a lot ! :D
