### ISSUE TITLE
Placeholders and marrytp

### ISSUE THREAD

**Issue by FaMa91** [GeorgH93/MarriageMaster#40]
Hi, nice plugin but we have a problem. Players can tp to their partners but there isn't confirm from the partner before the tp, this is a problem when someone is engaged in combat and a some point the 1vs1 becomes 2vs1. We would like to have a command that parter has to run to accept the tp, this way we can deny the accept command during the combat.

To do this by ourself we tried to make a custom command with another plugin, but placeholder doesn't seem to work with PlaceholderAPI, we've tried to follow the placeholder's wiki page and even tried a lot of variants but nothing. MarriageMaster appears in the papi list so we don't understand where the problem is.

We have MarriageMaster 1.31.8, who has been deleted from spigot but we haven't found the reason, for now our version run pretty well if we don't consider placeholders.

Thank you in advace!

**Comment by GeorgH93** [comment]
Hi,

I will add an option for that with the v2.0 update.
The placeholders for v1.x builds are not implemented by myself and I can therefor not offer support for problems with them.
v1.31.8 is fine, I probably just forgot to mirror the update to spigot.

Best regards
Georg

**Comment by GeorgH93** [comment]
I have added an option that requires players to accept the teleport to the V2.0 builds.
You can find more info about the V2.0 pre release version here: https://www.spigotmc.org/threads/marriage-master-mc-1-7-1-13.127262/page-13#post-2984833 , V2.0 will be released once I have finished updating it to fully support MC 1.13. You can find the builds here: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/
