### ISSUE TITLE
Disconnect issues

### ISSUE THREAD

**Issue by JokerLiuPro** [GeorgH93/MarriageMaster#41]
I get disconnect after type /marry sethome, /marry home, /marry gift... etc
https://pastebin.com/hh1aBVpJ

Server version: Paper(518) 1.13.2-R0.1-SNAPSHOT
MarriageMaster v2.0-RC2-SNAPSHOT-T20190115155843
PCGF_PluginLib v1.0.6-SNAPSHOT-T20190115150732

**Comment by GeorgH93** [comment]
Thanks for the report. Bug should be fixed with: https://ci.pcgamingfreaks.at/job/PluginLib/221/artifact/target/PluginLib-1.0.6-SNAPSHOT.jar and https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/47/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by JokerLiuPro** [comment]
confirm fixed, thanks
