### ISSUE TITLE
Children / Ability to marry with 3/4 players.

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#5]
Hello,

You said me in march 2016 that the release of this 3 features will be very soon, but we are in December and there is nothing.

Thanks for your answer !

**Comment by TheIntelloBox** [comment]
Hi,

When will be the children in the plugin ? :(

Thanks ! :D 
TheIntelloBox.

**Comment by TheIntelloBox** [comment]
?

**Comment by GeorgH93** [comment]
I am sorry, I don't know.
I don't have much time right now, sorry.

**Comment by TheIntelloBox** [comment]
?

**Comment by TheIntelloBox** [comment]
?

**Comment by TheIntelloBox** [comment]
Hi,

Have you got informations about children ?

**Comment by GeorgH93** [comment]
Closing this in favor of #46
