### ISSUE TITLE
Permissions doesn't work 

### ISSUE THREAD

**Issue by AccioAce** [GeorgH93/MarriageMaster#56]
Hello Author,
It seems like none of the permissions works at all for MarriageMaster. For example "marry.admin".

**Comment by GeorgH93** [comment]
Which values are you using for the config options `Permissions` and `VaultPermissions`?
What's your server version?
What's your MarriageMaster version?
What's your Vault version?
Which permission plugin (and version) are you using?

**Comment by AccioAce** [comment]
Which values are you using for the config options Permissions and VaultPermissions? They are both set to true as default
What's your server version? 1.14.1
What's your MarriageMaster version? Latest updated one
What's your Vault version? latest updated
Which permission plugin (and version) are you using? GroupManager

**Comment by GeorgH93** [comment]
Please try to disable the `VaultPermissions` option.
