### ISSUE TITLE
Players can't divorce on their own

### ISSUE THREAD

**Issue by Qinak** [GeorgH93/MarriageMaster#58]
**Marriage Master:** 2.0-RC2-SNAPSHOT-T20190528181130
**PCGF PluginLib:** 1.0.11-SNAPSHOT-T20190528222002
**Server:** git-Spigot-1a3504a-dfa7583 (MC: 1.13.2)

Using the default generated config with only this changed to false `DivorceRequiresPriest: false` and no permissions negated, players can't divorce when doing `/marry divorce`.
They only receive the help message "`/marry divorce - To leave your partner.`"

**Comment by GeorgH93** [comment]
Thanks for the report.
This build should fix the problem: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/71/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by Qinak** [comment]
Thanks!

It says the players doesn't have permission to do `/marry divorce`, however it does show up as an alternative when they do `/marry help`. I want players to only be able to self divorce, not self marry.
Is that possible?

**Config:**
```
RequirePriest: true
DivorceRequiresPriest: false
BothPlayersOnDivorce: false
OtherPlayerOnSelfDivorce: false
```

**Permissions:**
```
    - -marry.chat*
    - -marry.gift
    - -marry.pvp*
    - -marry.tp
    - -marry.home
    - -marry.delhome
    - -marry.sethome
```

**Comment by GeorgH93** [comment]
When `DivorceRequiresPriest` is set to `false` it should be possible for players with the `marry.selfdivorce` permission (the permission should be given to players by default).
I have fixed a couple of permission and settings related bugs. Please try this build: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/73/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by Qinak** [comment]
Thank you!

Is it possible to make some "accept" permission, so people without it can't accept a request?

**Comment by GeorgH93** [comment]
Here you go: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/77/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar
This build adds the "marry.accept" permission (will be given to users by default).

Please note that without the "marry.accept" permission players won't be able to accept any request (including tp requests and anything that might be added in the future).

**Comment by Qinak** [comment]
Thank you for adding it so fast!

I noticed if `RequirePriest: false` and `AllowPolygamy: false`, a player can send multiple marry requests to players, allowing them to accept and being married to that player.

Some things that would be nice:
Players without `marry.accept` can't receive requests.
Doing `/marry divorce` sends you a confirmation if you're trying to self divorce.

**Comment by GeorgH93** [comment]
Thanks for reporting.
The bug with the wrong names should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/79/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

I have created new issues for the other stuff as they will probably take a bit longer to fix.


> Doing `/marry divorce` sends you a confirmation if you're trying to self divorce.
Not sure what the value of having to accept your own divorce request would be.

**Comment by Qinak** [comment]
Thank you, I understand that.

That was just more like a precaution thought. Some people are not smart enough and really need to confirm some things on the server, especially when it comes to economy.

Anyhow, I greatly appreciate your work. Thanks again!
