### ISSUE TITLE
<statusheart>

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#6]
Hello !

Does the <statusheart> work on the V.2 ? Because when I put in the tchat, the players who are not married, doesn't have the grey heart.

Thanks !

**Comment by GeorgH93** [comment]
Hey!

With the V2.0 I have streamlined a lot of the placeholders. Therefor some of the old placeholders have changed. It's now: {StatusHeart}

Best regards
Georg

**Comment by TheIntelloBox** [comment]
Hello !

Okay, thanks.
I have a little problem. See this screen : http://zupimages.net/up/17/07/hsqw.jpg
The player who isn't married has directly the grey heart behind the > whereas the player who is married has a space after the heart.

Thanks !

**Comment by GeorgH93** [comment]
Hey, should be fixed now: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/11/artifact/target/MarriageMaster-2.0-SNAPSHOT.jar

**Comment by TheIntelloBox** [comment]
Hello ! :D 

Thanks a lot. :)
When will the children be implemented do you think ?

**Comment by GeorgH93** [comment]
Hey,

I haven't had much time lately cause of university. But the semester is over end of the week and I will start implementing it after that.
