### ISSUE TITLE
Custom language broken

### ISSUE THREAD

**Issue by Qinak** [GeorgH93/MarriageMaster#62]
Something made my language file stop working when it automatically updated to `2.0-RC2-SNAPSHOT-T20190626214956-b90` (https://pastebin.com/bAQRpR08) I restarted the server, it showed this: https://pastebin.com/x6Qx40zG

I also checked and compared a new generated en.yml to my custom lang, nothing where gone or changed.

**Comment by GeorgH93** [comment]
Could you please share your language file with me

**Comment by Qinak** [comment]
https://pastebin.com/Qm93AiGU

**Comment by GeorgH93** [comment]
The confirmation messages didn't contain a valid string for some reason.
This should fix is: https://pastebin.com/ECT8u5D2

**Comment by Qinak** [comment]
Thank you!
