### ISSUE TITLE
No one can marry tp

### ISSUE THREAD

**Issue by MithrandirCraft** [GeorgH93/MarriageMaster#7]
No one can marry tp no matter if OP or having the marry.tp permission.
No errors on console.

Mariage master v.1.29.13
Spigot for mc 1.11.2

**Comment by GeorgH93** [comment]
Can you please provide me with more details.
is there any message (like that the player was teleported)? Do you have economy enabled?

**Comment by MithrandirCraft** [comment]
- No message, just the generic insuficient permission message. And as I said, no error in console... :(
- I do have economy enabled.

**Comment by GeorgH93** [comment]
Since this seems to be a problem with the permissions I would need some more details.
Is "Permissions" enabled in the plugin config?
Is "VaultPermissions" enabled in the plugin config?
Can OPs still teleport?
Which permission plugin are you using?
If you have "VaultPermissions" enabled, which version of Vault are you using?

**Comment by MithrandirCraft** [comment]
Permissions: true
VaultPermissions: true
No one can teleport, not even OP
Permission plugin: PEX
Vault permissions is enabled, however I don't use VaultPermissions. This is just on by default, it never gave any issues. I may disable it anyway.
+ Other commands don't work either, globally in all of the network.

**Comment by GeorgH93** [comment]
This sounds like the problem lays on the bungee side of the plugin. Do you have the plugin installed on your bungee cord server?
If so:
Are the commands that not work: chat (if enabled in the config), home (if enabled in the config), tp (if enabled in the config), reload and update? They should still be listed in the help.
Do you have any permission plugin on your BungeeCord? Is the permission setup still correct (maybe an update has changed or reset the permissions)?

**Comment by TheIntelloBox** [comment]
On my single server (I don't have Bungee), we can do /marry tp without problems.

**Comment by MithrandirCraft** [comment]
yyyyeeeah.... I just noticed somehow the default rank had negative permission"-marry.user" attatched... I don't think that's very good.
I will slowly retrieve and close this ticket if that was the issue...
