### ISSUE TITLE
bring back the old placeholder format

### ISSUE THREAD

**Issue by mcannie97** [GeorgH93/MarriageMaster#70]
### Feature request

**Feature description**
Could you please bring back the old papi placeholders besides these new ones?

I am using `%marriagemaster_married% %marriagemaster_partner%` for chat hovers
on the old version of the plugin, this would give a grey/red hart (depending on if the person was married) and the username of the partner if the person was married/empty string if the person wasn't married.  

**How the feature is useful**
With the new version of the plugin, it looks like this: 
![image](https://user-images.githubusercontent.com/22767063/61540230-8ace1780-aa3d-11e9-896e-7fb27fff66dc.png)

which is not really pretty ;P

if it is possible to bring the old format back (perhaps with different placeholder names) that would be greatly appreciated <3

**Comment by GeorgH93** [comment]
You can change the `not married` text in the language file (under `Placeholders.NotMarried.Default`).
The heart just uses a different placeholder now: `%marriagemaster_statusheart%`.
