### ISSUE TITLE
Console error. Spigot 1.13.2

### ISSUE THREAD

**Issue by Fiks75** [GeorgH93/MarriageMaster#73]
### Information
**Environment information**
*Plugin + server version info*:

```

24.07 15:00:10 [Server] INFO ##### Start Marriage Master version info #####
24.07 15:00:10 [Server] INFO Marriage Master: 2.0.7-Release
24.07 15:00:10 [Server] INFO Server: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
24.07 15:00:10 [Server] INFO MVdWPlaceholderAPI: 2.5.1
24.07 15:00:10 [Server] INFO PlaceholderAPI: 2.10.3
24.07 15:00:10 [Server] INFO #####  End Marriage Master version info  #####

```

*Online mode*: no

*BungeeCord*: no

**Server/crash log**

```

https://pastebin.com/buJXQhJB

```

**Plugin config (optional)**

```

https://gist.github.com/Fiks75/637653cbc5d7678d7a39fc4d524fd49a

```

### Details
**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
Thanks for the report.
This is fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/97/artifact/artifacts/MarriageMaster-2.0.8-RC3-Release.jar
