### ISSUE TITLE
marry list - missing commands

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#74]
The command /marry list is missing some commands with German translation. The following commands are not explained: kiss, gift, chat, chattoggle, hug. Since ingame access is very handy, it would be cool if you could add them :)

MarriageMaster: 2.0.8
Paper 1.13.2 - 641

**Comment by GeorgH93** [comment]
Could you please send me your language file?

**Comment by TheoRetisch1** [comment]
Thanks for the hint! I just had it regenerated, it works wonderfully! Have a great day :)
