### ISSUE TITLE
Chattoggle does not work with ChatControl

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#75]
Unfortunately the function /marry chattoggle does not work together with ChatControlPro. The message is sent to the marry channel, but also appears in the global chat. Since ChatControl is one of the biggest and most popular plugins it would be cool to create compatibility here.

MarriageMaster: 2.0.8
Paper 1.13.2 - 641
ChatControlPro 8.2.6

**Comment by GeorgH93** [comment]
ChatControlPro is not a free plugin, I will not add support for it.

**Comment by TheoRetisch1** [comment]
Ok, if we phrase it differently, could you please add support for ChatControl? ChatControl has the same problems (ChatControl Pro only adds a few features) and is a free, supported plugin with 500000+ downloads :)

**Comment by TheoRetisch1** [comment]
Ok fuck, the free version 5.8.4 does not have the problem with the same config. I should stop making random assumptions :(. Thank you anyway.
