### ISSUE TITLE
Error config BungeeCord since 2.0

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#76]
Hello,

Having regenerated all the files of configs in view of the new update because it did not really work anymore, I have a rather odd error on the bungeecord side, I have the latest version of waterfall in 1.14.4 and the latest version paperspigot in 1.14.4 as well as the latest version of the plugin.

Error: https://pastebin.com/smeWKfLh
Config: https://pastebin.com/tSVxtydQ

I also have this error on the paper servers: https://pastebin.com/UTsCLhhz

**Comment by GeorgH93** [comment]
Bungee config line 87, there is a space between UUID_Type and the : char that should not be there.

Your MySQL user does not have the "REFERENCES" privilege, please add it.

**Comment by jere62smi** [comment]
Actually for the bungee error this is fixed and it seems that you have left a default space in the config file.
As for the errors for the database, I'm going to look at it, I'll let you know.
