### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by Artuto** [GeorgH93/MarriageMaster#79]
### Help request

**Problem**
Booting the plugin got this error https://gist.github.com/Artuto/a677ae7edb380e6dfeda4b13f1f13694

**What I have tried**
No idea why this happened. It was fine before

**Comment by GeorgH93** [comment]
Could you please provide me your config file and the output of the following SQL command: `SHOW CREATE TABLE marry_partners;` (you might have to adjust the table name depending on your config)

**Comment by Artuto** [comment]
`CREATE TABLE `marry_partners` (
  `marry_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player1` int(10) unsigned NOT NULL,
  `player2` int(10) unsigned NOT NULL,
  `priest` int(10) unsigned DEFAULT NULL,
  `pvp_state` tinyint(1) NOT NULL DEFAULT '0',
  `date` datetime NOT NULL DEFAULT '2019-07-23 23:20:21',
  `surname` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`marry_id`),
  KEY `player1_idx` (`player1`),
  KEY `player2_idx` (`player2`),
  KEY `priest_idx` (`priest`),
  CONSTRAINT `fk_marry_partners_marry_players_player1` FOREIGN KEY (`player1`) REFERENCES `marry_players` (`player_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_marry_partners_marry_players_player2` FOREIGN KEY (`player2`) REFERENCES `marry_players` (`player_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_marry_partners_marry_players_priest` FOREIGN KEY (`priest`) REFERENCES `marry_players` (`player_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1`

config (i removed the db values) https://gist.github.com/Artuto/de7565e74d8a05c10fd5bbcd00647c2c

**Comment by GeorgH93** [comment]
Have you been using Marriage Master v1.x with this database previously?

**Comment by Artuto** [comment]
I updated Marriage Master to MC 1.14.4, so yeah probably (I was on 1.13.2 before)

**Comment by GeorgH93** [comment]
Please modify the tables section of your config like that:
```
    Tables:
      User: marry_players
      Partner: marry_partners
      Home: marry_home
      Priests: marry_priests
      Fields:
        PriestID: priest_id
```

**Comment by Artuto** [comment]
That worked, thanks!
