### ISSUE TITLE
Migrating file based storage into MySQL is broken

### ISSUE THREAD

**Issue by M1staAwesome** [GeorgH93/MarriageMaster#82]
### Help request

**Problem**
The `Migrating file based storage into MySQL` part of the wiki isn't working, as the link to download the jar to convert your server files is down.

**What I have tried**
Nothing, as there is nothing for me to do.

**Comment by GeorgH93** [comment]
Looks like I have forgotten to remove the page. Was for v1 only.
Migrating to MySQL can currently only be done by hand (export the SQL lite data and import it in MySQL). Support for automated migration will come at a late point.

**Comment by M1staAwesome** [comment]
Alright, thanks
