### ISSUE TITLE
Stopping marry sethome from working in certain worlds

### ISSUE THREAD

**Issue by MithrandirCraft** [GeorgH93/MarriageMaster#84]
**Feature description**
An configuration which allows for disabling certain worlds where using /marry sethome wouldn't be allowed, or a permission for allowing disallowing the usage of /marry sethome (which would be just as usefull since permissions can be negated per world) 

**How the feature is useful**
It would allow for me to stop users from setting homes in an rpg world where I just don't want them to spawn inside hard to access areas.

**Comment by GeorgH93** [comment]
There already are permissions for that.
`marry.home` controls if a player can teleport to a home
`marry.sethome` controls if a player can set a home
`marry.delhome` controls if a player can delete a home
`marry.home.*` combines the previous 3 in one permission

You should be able to give fine control over what is allowed in which world through your permission plugin.

**Comment by MithrandirCraft** [comment]
Ah ok. I checked the bukkit permission list which is probably outdated.
