### ISSUE TITLE
Error sql with version 2.0

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#87]
Hello,

I can not import my old data since update 2.0. It seems that a field is not a key. Can you help me plz.
https://pastebin.com/XGQtmdFU

**Comment by GeorgH93** [comment]
Can you please send me your config

**Comment by jere62smi** [comment]
https://pastebin.com/wiXrhvA8

**Comment by GeorgH93** [comment]
That's the BungeeCord config file. And your error is form Bukkit. But I would assume that your Bukkit config is missing the `PriestID: priest_id` (line 74 in the config you have sent).

**Comment by jere62smi** [comment]
https://pastebin.com/G3tiz1ri
and suddenly I add that you indicated me in this file?

**Comment by GeorgH93** [comment]
Please edit that file by adding
```
      Fields:
        PriestID: priest_id
```
in a new line after line 41.
Like that: https://pastebin.com/Ak3musap

**Comment by jere62smi** [comment]
Okay thank you, this error is fixe but i have a new error with bungee: https://pastebin.com/hUHLjJWE

**Comment by GeorgH93** [comment]
Could you please run this `SHOW CREATE TABLE marry_partners;` command on your MySQL server (with the database you are using selected) and provide me with the result.

**Comment by jere62smi** [comment]
The problem came from me, I corrected, thank you.
