### ISSUE TITLE
Problems with multi marriages and chat

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [GeorgH93/MarriageMaster#88]
### Information
**Environment information**
*Plugin + server version info*:

```

19.08 14:33:43 [Server] INFO ##### Start Marriage Master version info #####
19.08 14:33:43 [Server] INFO Marriage Master: 2.0.10-Release
19.08 14:33:43 [Server] INFO Server: git-Paper-115 (MC: 1.14.3)
19.08 14:33:43 [Server] INFO Vault: 1.6.11
19.08 14:33:43 [Server] INFO MVdWPlaceholderAPI: 2.5.1
19.08 14:33:43 [Server] INFO PlaceholderAPI: 2.10.2
19.08 14:33:43 [Server] INFO #####  End Marriage Master version info  #####


```

*Online mode*: no

*BungeeCord*: yes
**Server/crash log**

```

<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```

<!-- Replace this with details about your config -->

```

### Details
**Description**  
Since update to 2.0 i have a few problems with Marriage.

1. Prefix on line beggining stopped working and its only after marry and not always. It worked before. I know I can use placegolder, but the only one with heart is status_heart and its displaying gray placeholder if someone is not married and i want heart only if someone has his love.

2. When using multi marriages /marry kiss stopped working. Idk if it should be like that and if yes, there should be some error line to inform that if someone has more than one marriage he shpuld use right mouse button

3. When using multi marriages it does not show, when partners are joining server.

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
1. Which chat plugin (in which version) are you using? You can use the `%marriagemaster_heart%` placeholder, it will show a read heart if the player is married and the `Placeholders.NotMarried.Default` option from the language file if the player is not married, to not show anything if the player is not married you can change it to `Default: ""` in your language file.
2. What is the behavior you are seeing? It should take the partner that is nearest to you and you can overwrite the partner to use by using `/marry kiss <partnername>`
3. Please try if this fixes the issue for you: https://ci.pcgamingfreaks.at/job/MarriageMaster/116/artifact/artifacts/MarriageMaster-2.0.10-RC2-Release.jar

**Comment by Kryniowesegryderiusz** [comment]
1. CMI in 8.6.9.4 Can i change %marriagemaster_heart%? Im trying to do "<heart> " (with space) so normal players wouldnt have double space before nick.

2. That player is offline

3.  ill try

**Comment by GeorgH93** [comment]
1. CMI is a premium plugin so I will not fix it. Currently there is no option, so you would have to modify the source code for now.
2. Can you please send me your config
3.
4. You specify a player like `/marry seen <partnername>`, help seems to miss the parameter, will be fixed with the next update.

**Comment by Kryniowesegryderiusz** [comment]
1. I know its Premium, but a lot of server is acctually using it. But the most needed feature is to specify the "heart" placeholder, if someone is married, as we can if he isnt.
2. https://pastebin.com/scJUySQG

**Comment by GeorgH93** [comment]
1. That might be true, but I won't by a plugin just to fix a incompatibility/misbehavior with my *free and open source* plugin. I have opened a issue for the placeholder customization, you can follow it here: https://github.com/GeorgH93/MarriageMaster/issues/89
2. Please try to set the `UseUUIDs` option to `true`

**Comment by Kryniowesegryderiusz** [comment]
2. Wouldnt it break acctuall marriages?

wt., 20 sie 2019 o 00:30 GeorgH93 <notifications@github.com> napisał(a):

**Comment by GeorgH93** [comment]
It should not, however if you are behind a BungeeCord proxy you should set the `UUID_Type` accordingly to be on the save side.

**Comment by Kryniowesegryderiusz** [comment]
5. One of players said that he see "This partners are online:
{OnlinePartners}" with that placeholder, which is not changed.

wt., 20 sie 2019 o 00:31 Konrad Boś <mrkondziou@gmail.com> napisał(a):

**Comment by GeorgH93** [comment]
Should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/117/artifact/artifacts/MarriageMaster-2.0.11-RC3-Release.jar
