### ISSUE TITLE
Bug chat

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#91]
Hello,

Since the new version 2.0 of MarriageMaster, the marriage proposal with the plugin Deluxechat no longer works. I have an error in the console and a screen of the cat.

https://pastebin.com/6rnYifU7
https://prnt.sc/oxnky3

I have the latest version of Marriagemaster and Paper.

**Comment by GeorgH93** [comment]
Problem is caused by DeluxeChat not Marriage Master.

**Comment by jere62smi** [comment]
Certainly but why since your update, there is this problem, you changed some things?

**Comment by GeorgH93** [comment]
The problem was introduced with the DeluxeChat update 1.14.2 and only affects 1.14 servers.
It is also affects Marriage Master v1.31.16 or any other plugin that is using the player.chat() method from the main thread.

**Comment by jere62smi** [comment]
Okay, I contacted them, if you can support my request on their discord, that would be great;)

**Comment by GeorgH93** [comment]
I am sorry, but I will not use discord.
I have sent the dev a pm on spigot, no Idea if he will read it.
