### ISSUE TITLE
1.14.4 /marry gift not gifting the whole stack of item(s)

### ISSUE THREAD

**Issue by CaptainAmpersand** [GeorgH93/MarriageMaster#95]
### Help request

**Problem**

Regular players, when using /marry gift, don't receive the entire stack. For example, I sent a stack of 64 steak, my alt only received 33 steak.

**What I have tried**

I tried to go through the configs, I tried to find if it was a permission node that I missed, I tried to find any kind of other person using this plugin to try and explain it, but there was no way to really figure it out. Now, I come to you, begging to know how I can fix such a debacle.

**Comment by GeorgH93** [comment]
Please provide me with the output of `/marry version`

**Comment by CaptainAmpersand** [comment]
https://i.imgur.com/LplKQie.png

**Comment by GeorgH93** [comment]
Please try if this build solves the problem: https://ci.pcgamingfreaks.at/job/MarriageMaster/126/artifact/artifacts/MarriageMaster-2.0.14-RC1-Release.jar

**Comment by CaptainAmpersand** [comment]
Confirming that this fixed the issue. Great work GeorgH93!
