### ISSUE TITLE
Health regen doesn't work

### ISSUE THREAD

**Issue by Lethgir** [GeorgH93/MarriageMaster#96]
### Information
**Environment information**
*Plugin + server version info*: Plugin 2.0.14 spigot 1.14.4
```
16:28:09 [INFOS] Prod1.14 > ##### Start Marriage Master version info #####
16:28:09 [INFOS] Prod1.14 > Marriage Master: 2.0.14-Release
16:28:09 [INFOS] Prod1.14 > Server: git-Spigot-065a373-763e560 (MC: 1.14.4)
16:28:09 [INFOS] Prod1.14 > Minepacks: 2.0.10-Release
16:28:09 [INFOS] Prod1.14 > PlaceholderAPI: 2.10.3
16:28:09 [INFOS] Prod1.14 > #####  End Marriage Master version info  #####
```

*Online mode*: no (with bungeecord)

*BungeeCord*: yes 

**Plugin config (optional)**
```
HealthRegain:
Enable: true
Multiplier: 1000

Range:
Marry: 25.0
Divorce: 25.0
Backpack: 5
Gift: 0
Kiss: 2
KissInteract: 5
Hug: 2
HearthVisible: 128
BonusXP: 10.0
Heal: 3
```

### Details
**Description**  
Iit looks health regen doesn't work, the regen is the same than vanilla no matter the value of multiplier (2 or 1000).

**Steps to reproduce**  
Marry two players
Give damage to one of them
Check the health regen
Divoce two players
Give damage to one of them
Check the health regen

Both regen are the same

**Expected behavior**  
The player should have a better regen than vanilla.

**Comment by GeorgH93** [comment]
I am not able to reproduce this problem. With a multiplier of 1000 the player should be at max health basically instant.
For my testing I set the multi to 1000, drop the hp of a married player to 1 heart, and place the player 20 blocks away form the partner, then I eat something so that the player starts healing, it will heal at a rate of about ½ heart every time it heals, than I teleport the player to it's partner (/marry tp) and the next time the health increases it goes to 100%.

It could be caused by some other plugin, could you provide me with a list of other installed plugins?

**Comment by Lethgir** [comment]
I tried the same thing than you and player is still not healed.

Plugins (54): AdvancedAchievements, BlockParticles, BlowableObsidians, BungeeBridgeC, BungeeJoinMessages, BungeeTabListPlus, BungeeTeleport, BuycraftX, ChatManager, Citizens, CitizensCMD, CMI, ConsoleSpamFix, CrazyAuctions, CrazyCrates, CrazyEnchantments, EnchantableBlocks, Factions, FactionsTop, Itemizer, JupiterCore, LuckPerms, MarriageMaster, MassiveBooks, MassiveCore, Minepacks, MMOItems, MovingDevApi, Multiverse-Core, MythicArtifacts, MythicMobs, MythicMobsExtension, obsidianraider, OldCombatMechanics, PlaceholderAPI, PlugMan, ProtocolLib, QuantumShop, RandomTeleport, Rankup, RewardPRO, SkMorkaz, SkQuery, skRayFall, Skript, skUtilities, SuperTrails, VariableTime, Vault, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by GeorgH93** [comment]
Problem is caused by OldCombatMechanics. The plugin does not have an API so the only way to make the healing bonus work is by disabling the `old-player-regen` in the OldCombatMechanics config.

**Comment by Lethgir** [comment]
It works well, many thanks for the full investigation !
